### ISSUE TITLE
Design Site Map

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#1]

**Comment by chloeatplay** [comment]
![discovery_sitemap-01](https://f.cloud.github.com/assets/1945209/1717878/c7934cbe-61d5-11e3-9c85-1c1c00d06c9c.png)

cc @threeqube @cmcavoy  // Will elaborate/present on Thu. design call as well :dancer:

**Comment by threeqube** [comment]
This makes sense @chloeatplay. My initial question had to do with the dashboard piece but thanks for clearing that up. :+1:

**Comment by iamjessklein** [comment]
Just want to reiterate some notes from our conversation last week about the site map here for documentation purposes. We discussed considering not surfacing the badge directory to the user - but really focusing on making this a badge pathway directory - a la DIY.org.

**Comment by chloeatplay** [comment]
On second thought I think we will surface badges along with pathways in the gallery, but for MVP keep the badge page to a standard view, as seen for example in badgekit - for consistency. @iamjessklein I think what we discussed was that we will explore the directory features you suggested in your "yelp for badges" directory wireframes, such as ratings etc further down the line. I am sure this will all become more clear as we build the wireframes :)

**Comment by threeqube** [comment]
This works for me. I have a hard time wrapping my head around not surfacing the badge directory since that is the building block for the pathways...
