### ISSUE TITLE
Design Badges Page (Desktop)

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#10]
We need to design a badge page for the directory. cc/ @iamjessklein @xmatthewx

**Comment by xmatthewx** [comment]
hey Chloe ... I made a quick at-a-glance chart of all the different places and ways a badge might be displayed. You can [view it in gdrive](https://docs.google.com/a/mozilla.com/spreadsheet/ccc?key=0AvrbDAen9prkdC1CT2h1Vk9sMWJoWXVublhYaFlJNGc&usp=sharing) with your moz address. Feel free to edit. 

I think we should have 2 or 3 ways of displaying a badge, with either more or less detail ... 2 or 3 ways that fit 85% of the use cases.

**Comment by threeqube** [comment]
@xmatthewx I think the there will be 2 use cases here:
- (1) display of an earned badge instance: the earned badge of a logged in user being pulled in from their backpack
- (2) display of an earnable badge class with all the associated metadata and criteria information: the badge class that the earner can add to a pathway or favorite

**Comment by xmatthewx** [comment]
@threeqube - agreed. 

```
                  (a) small    (b) detailed    
             --|-------------|--------------|--
  (1) earned   |   facebook  |   resume     |   links to issuer or evidence??
             --|-------------|--------------|--
(2) earnable   |    tumblr   |   website    |   links to issuer's badge info
             --|-------------|--------------|--
               |             |              |
```
- (a) display image, title, link
- (b) display image, title, link, criteria, etc

**Comment by threeqube** [comment]
@xmatthewx For this instance sub facebook and tumblr for discovery tool site. So:

```
                  (a) small    (b) detailed    
             --|-------------|--------------|--
  (1) earned   |  discovery  |   resume     |   links to issuer and evidence if available
             --|-------------|--------------|--
(2) earnable   |  discovery  |   website    |   links to issuer's badge info
             --|-------------|--------------|--
               |             |              |
```

What do you mean by resume?

By website I assume you mean issuer website with criteria information.

**Comment by chloeatplay** [comment]
Hi @xmatthewx , thanks for these! I am not sure I get the table content above, maybe we can go over it this week? I understand the user cases @threeqube mentions , and am looking for UX templates that you might have already developed for Badgekit...
