### ISSUE TITLE
Conduct All Interviews for Tech Pathways

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#103]
@LucasBlair will complete all the interviews with the tech issuers and earners. :computer: :thumbsup: :rocket:

**Comment by chloeatplay** [comment]
I believe this is complete, aside from a few extras. @LucasBlair let me know if you want to close the issue.

**Comment by LucasBlair** [comment]
Yes we are getting close. Still have to do Brian and meet with the TopCoder folks. The rest I believe we can fill in with industry research.
