### ISSUE TITLE
Conduct All Interviews for Service Pathways

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#104]
@LucasBlair will interview all the service issuers and earners :cocktail: :coffee: :spaghetti:

**Comment by chloeatplay** [comment]
Moving to a further milestone @LucasBlair

**Comment by LucasBlair** [comment]
Probably a good idea until we nail down Sodexo and UPMC.

**Comment by LucasBlair** [comment]
Issuers done. Earners will happen in the next couple weeks.

**Comment by threeqube** [comment]
:+1:
