### ISSUE TITLE
What is the actual goal of this project?

### ISSUE THREAD

**Issue by sn3ek** [mozilla/openbadges-discovery#11]
Hi,
I'm following the project. But I barely can see what the actual goal is. What should be accomplished? Do you "just" want to build different clients such as mobile app, web app and desktop app? What's the backend? 

I couldn't attend to any community call, yet. Are there more information about the goal, I haven't seen yet? 

Thank you :)

**Comment by jadeforester** [comment]
Hi,

Thanks for reaching out! Our team often blogs about the various projects we're working on - let me share some blog posts with you that might provide a little context to Discovery, Pathways and the Badge Directory:

From @iamjessklein, our Creative Lead: http://jessicaklein.blogspot.co.uk/2013/07/badgopolis-form-follows-emotion.html 
Also from Jess, specifically on badge directory: http://jessicaklein.blogspot.co.uk/2013/11/badge-directory-yelp-for-badges.html
From Design and Product Strategist @chloeatplay on Pathways (including a link to a pathways prototype she and @stenington put together): http://chloeatplay.tumblr.com/post/65950219599/badgekit-pathways-and-paving-the-path-to-playful

Our Director of Badge System Design + Implementation @carlacasilli has written a series of blog posts on badge pathwys - you can find them here: http://carlacasilli.wordpress.com/category/badge-pathways/

If you have further questions, feel free to reach out to badges[at]mozillafoundation[dot]org as well.
- Jade

**Comment by sn3ek** [comment]
Thank you jade. I guess for the beginning it will give me a nice overview :)

A question do I have: I'm a Ruby on Rails developer and I also have some ideas about building projects with achievement systems and pathways for students. Maybe there is something I could bring into the project - ideas, implementations etc? 

I have seen the prototype will be implemented with meteor?

**Comment by jadeforester** [comment]
Maybe you'd be interested in joining our Community Calls on Wednesdays? They are a great place for news and updates on badges projects and for 2-3 community members to give short presentations and discuss things with the broader community.

More info: http://bit.ly/OpenBadgesCommunityCalls

We also hold a Research + Badge System Design Call in the hour before the Community Calls every Wednesday, for a deeper discussion of research and system design with a presentation from one community member. These calls also give presenters a chance to ask questions and get feedback from the group.

More info: http://bit.ly/ob-research

**Comment by sn3ek** [comment]
Thank you @jadeforester I plan to attend on the call on wednesday. Thank you for the links!
