### ISSUE TITLE
Create Pathway FrameWork document

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#115]
We should create a document that explains the pathway framework thinking and theory. So people can use this to create their own systems. Cc @ghami @chloeatplay to contribute. Might use @zzzndr 's illustration chops for this as well.

**Comment by ghami** [comment]
Have begun to put some ideas together re this in Pathway google doc under heading: Open Badges Discovery / Pathways project - Approach. Possible structure for people creating own pathways / systems could be:
1. Create pathway tree: underpinning skills (roots); core skills and attributes (trunk); specialisms (branches)
2. For each pathway (roots, core and specific branch): use Industry Competency Model to document specific skills / requirements 
3. Translate Industry Competency Model into badge pathway
4. Use tag template (possibly using Holland Codes) to define tags for pathway
