### ISSUE TITLE
Write White Paper

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#116]
TBD. Adding here so we don't forget we need to do this :dancer: cc/ @LucasBlair  @ghami @threeqube

**Comment by ghami** [comment]
Have begun to put some ideas together re this in Pathway google doc under heading: Open Badges Discovery / Pathways project - Approach.

**Comment by chloeatplay** [comment]
@ghami :thumbsup: added comments to the doc.
