### ISSUE TITLE
Create Visual Study

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#117]
Create a visual study of the elements that go into the websites' UI :art: :triangular_ruler: :scissors: Experiment with color schemes from both splash page #13 and the attached 
![screen shot 2014-02-21 at 12 53 17 pm 3](https://f.cloud.github.com/assets/1945209/2233616/f9ab9e88-9b2b-11e3-870b-72d02d305495.png)

cc @adiladiladil for good measure.

**Comment by zzzndr** [comment]
Here are 3 different visual language studies. 
Open Sans is used for the texts, choice of colors are on the Open Badges logo and the splash page.
Please take a look at the layout choices and colors.

Later i will upload the corresponding pages for the mobile layout 

1.
The rollover (yellow badges) of the badge could be something like
http://tympanus.net/Tutorials/CaptionHoverEffects/index5.html
![visualstudy1-01](https://f.cloud.github.com/assets/6721026/2245626/c30f3788-9d54-11e3-9e53-9d0926e62011.jpg)

2.
![visualstudy2-01-01](https://f.cloud.github.com/assets/6721026/2245629/c97dc328-9d54-11e3-8314-d811826db8d8.jpg)

3.
![visualstudy3-01-01](https://f.cloud.github.com/assets/6721026/2245635/d2933560-9d54-11e3-828c-6a1c9c81b2d6.jpg)

**Comment by threeqube** [comment]
cc/ @adiladiladil

**Comment by stenington** [comment]
@zzzndr Keep in mind hover effects can be difficult for mobile, although it looks like those examples you cited do work on mobile using touch events. They fire even when I'm not intending a touch, I'm intending to scroll though, which might be a potential source of frustration.

**Comment by zzzndr** [comment]
@stenington Ty, good points! I asumed that this could be solved with media queries? If not or it might be buggy I'll take it into account when implementing all the feedback

**Comment by stenington** [comment]
Yep, most likely solvable with media queries! Just keep in mind that you potentially have to provide two designs (desktop & mobile) and I potentially have to write more code. :)

**Comment by zzzndr** [comment]
here are the corresponding pages for the mobile layout

1.
![visualstudy1_mobile-01](https://f.cloud.github.com/assets/6721026/2258813/cea22ca2-9e2d-11e3-95b7-f63f5c145116.jpg)

2.
![visualstudy2_mobile-01](https://f.cloud.github.com/assets/6721026/2258815/d4f6aaec-9e2d-11e3-9c39-c11c44ec2f9e.jpg)

3.
![visualstudy3_mobile](https://f.cloud.github.com/assets/6721026/2258819/daf4ed1e-9e2d-11e3-80d8-ab1bc25dce0d.jpg)

**Comment by chloeatplay** [comment]
Great work @zzzndr . I like the second solution but also recognize that on mobile the layout in the first solution might work best. I also like the warm colors- but I think the blue on second would allow for more clarity and the badge visuals to pop out. Still it might be fun to add some colors to it, - have you thought of combining it with some bright colors like the pallete on the tiny games app? http://hideandseek.net/projects/tiny-games-app/ . In terms of icons I prefer the heart icon versus star and fork ones, since it probably resonates more with our average user. 
Mean while it would be nice to see in these studies some visual distinction between badges and pathways. Hope this helps :palm_tree: :sunglasses: :sunny:

**Comment by zzzndr** [comment]
Here are 2 new versions
I’m still trying to find a way to make the screens more playful, feedback is more then welcome (:

Visual study nr.4 desktop
https://redpen.io/qcbt8e

Visual study nr.4 mobile
https://redpen.io/bugvts

Visual study nr.5 desktop
https://redpen.io/nvazy1

Visual study nr.5 mobile
https://redpen.io/aoytgf

**Comment by chloeatplay** [comment]
Great work @zzzndr ! I really like the color pallete :art:  on nr4. as well as the button design and playful shades. The layout on nr.5 looks cleaner in terms of the white space. 
Added comments & questions in the redpens ^^

**Comment by threeqube** [comment]
Added a couple comments in directly. Agree with @chloeatplay, Great work @zzzndr!

**Comment by zzzndr** [comment]
The new versions can be found here!
Visual study nr.6 Desktop
https://redpen.io/ewb5xq

Visual study nr.6 Mobile
https://redpen.io/tmza7x

**Comment by chloeatplay** [comment]
Thanks @zzzndr, great work =) Left my comments in the redpen. Overall I would say we are almost there =) Would keep the bevel for now (buttons too) at the end of the final study. They are great for buttons that have to do with actions in the interface, like "pledge to do a pathway" etc.

**Comment by zzzndr** [comment]
New versions can be found here:

desktop
https://redpen.io/rd5xfe

mobile
https://redpen.io/q39rnc

Please pay specific attention to how the logo’s of the badge creators are positioned, there is a different design for the pathways & badges only to show us both options (:

**Comment by zzzndr** [comment]
here is a new version:
https://redpen.io/p24rhw

**Comment by chloeatplay** [comment]
:thumbsup: Closing this issue now :tada:

**Comment by threeqube** [comment]
:+1:

**Comment by zzzndr** [comment]
woop!
Does it make sense to create a wiki page?

**Comment by threeqube** [comment]
@zzzndr yes please! Something here would be great! https://github.com/mozilla/openbadges-discovery/wiki/_pages

**Comment by chloeatplay** [comment]
@threeqube @zzzndr yay for wiki pages, but lets create them once we have finalized designs and closed these issues. Right now designs are still in process so wiki pages might not reflect final designs :art: :squirrel:

**Comment by threeqube** [comment]
Totes. :+1:
