### ISSUE TITLE
Create quiz content

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadges-discovery#12]
When a user first starts, the discovery tool needs some context to get oriented and start generating recommended badges. We'll fulfill that with an initial strawman quiz. 

cc/ @emgollie

**Comment by chloeatplay** [comment]
Reassigning to @ghami. Once we have content for this we can connect to #44 and open an implementation ticket. 
@stenington would like your input about the simplest way to connect quiz results to the recommended listing.

**Comment by stenington** [comment]
I think the simplest way would be to translate the quiz results to search parameters to issue against the directory. That in turn calls into question the idea of tagging again, and whether we'll go with issuer-supplied tags only or have some sort of additional tags available, etc. 

I think maybe we need a discussion ticket for that, which I will open and link here.

**Comment by stenington** [comment]
Ok created #46

**Comment by chloeatplay** [comment]
@ghami moving this to the next milestone. @stenington moving to #46 to follow discussion.

**Comment by ghami** [comment]
Content in progress https://docs.google.com/presentation/d/1PHUJzSrB7dQ0rAdHlgzl4Dy2sqqnrCveRs9ZtQkzWn0/edit#slide=id.g2ac79fef6_06

**Comment by ghami** [comment]
Content created. Quiz prototype continued at #107
