### ISSUE TITLE
Persona log in progress indicator

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#121]
In using the app on staging, I've noticed that my expectation is that I'm logged in as soon as the Persona dialog appears, which isn't actually true. There's still a round-trip to the server that needs to happen, and I think during that period we might want to show a spinner or something to keep people from clicking things that spawn yet another Persona log-in window.

**Comment by chloeatplay** [comment]
:+1: 
also- with persona project being slowly closing as a Mozilla project, wondering if we should consider in the future some other sign in methods? (esp. popular with kids, like facebook etc)

**Comment by threeqube** [comment]
Other forms of authentication is something we should have a larger discussion about for sure. cc/ @cmcavoy and @iamjessklein for good measure.
