### ISSUE TITLE
Create Icons 

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#125]
Design the icons for the site, i.e. hearts, pathway icons, badge icons. 
We can explore using fontawesome or other open source icon libraries. For differentiating between pathways and badges as @zzzndr is starting to explore in #117 we can also create unique icons of it makes sense. I like the way DIY does the icons on top of the gallery boxes in this page: https://diy.org/completed.

**Comment by zzzndr** [comment]
Here is a list of the icons, did I miss any?

icons on top of badges
- wishlisted (heart)
- pathway
- badge

navigation menu pathway
- Personalise (mobile only)
- View Similar
- Add badges
- Add a note
- Remove parts

pathway badge icons
- Core badge
- Goal badge

**Comment by chloeatplay** [comment]
:thumbsup:

**Comment by zzzndr** [comment]
Here is an overview of the icons, please pay extra attention to the pathway & badge icon, they are  _new_ (:
https://redpen.io/4bf1j2

**Comment by zzzndr** [comment]
here is an updated overview of the icons:
https://redpen.io/rokh5w

**Comment by zzzndr** [comment]
Here is a new overview of the icons:
https://redpen.io/tmas2u

**Comment by zzzndr** [comment]
Here is a new overview of the icons:
https://redpen.io/nkj8y9

**Comment by chloeatplay** [comment]
:thumbsup: let's close this issue for now :)
