### ISSUE TITLE
Design UI for D5 / M5 Discovery Pathway Page, Pledged

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#126]
Once design of D4/M4 is finalized we can tackle this page per #119

**Comment by zzzndr** [comment]
Here are updated screens for desktop and mobile:
D5
https://redpen.io/yvafwq

D5 rollover
https://redpen.io/r3wse6

M5
https://redpen.io/8aosu1

**Comment by zzzndr** [comment]
Here is an updated screen for mobile:

M5
https://redpen.io/cmhy1w

**Comment by chloeatplay** [comment]
:+1:

**Comment by zzzndr** [comment]
Here are new screens with the tags:

Desktop
https://redpen.io/sxbyfq

Mobile
https://redpen.io/9kv4j3

**Comment by zzzndr** [comment]
Here are the screens for show how to edit your pathway name

desktop
https://redpen.io/qu1ec30365b9080d65

mobile
https://redpen.io/na02704d5323b09f00

**Comment by zzzndr** [comment]
Here is an enhanced pathway settings popup with the option to drop out of a pledged pathway. I tried to make the button to do so unobtrusive.

D5 pathway settings a
https://redpen.io/tg9a324b3246a1bcda

Clicking on the (x) right of the ‘Pledged’  will lead you to screen b

D5 pathway settings b
https://redpen.io/vkf85d3005a271f852

**Comment by chloeatplay** [comment]
Moved to #193
