### ISSUE TITLE
Design UI D9, D9a / M9a, M9b, M9c Discovery Pathway Page, Add a note

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#127]
Per #119

**Comment by zzzndr** [comment]
Here is the screen for desktop.
Later i will upload the corresponding pages for the mobile layout.

D9
https://redpen.io/bu1cea

D9A
https://redpen.io/y5vtho

**Comment by zzzndr** [comment]
Here are new screens with an updated navigation menu

D9
https://redpen.io/uhxfky

D9a
https://redpen.io/7ca4u6

**Comment by zzzndr** [comment]
here are 2 new variations of the navigation menu
https://redpen.io/eusyoc

**Comment by zzzndr** [comment]
here is the updated screen for the desktop + open menu without the icons
https://redpen.io/6rtakj

**Comment by zzzndr** [comment]
Here are updated screens for desktop and mobile:

D9
https://redpen.io/sq4th3

D9a
https://redpen.io/4sydz6

M9
https://redpen.io/9b85g3

M9a
https://redpen.io/htcesu

**Comment by zzzndr** [comment]
M9
https://redpen.io/cz7rbw
New cleaner design with only a hamburger menu

I’ve also updated #129 M8a for us to show this design on a non-pathway page.

**Comment by zzzndr** [comment]
Here are updated screens for mobile:

M9
https://redpen.io/52phzx

M9a
https://redpen.io/rsn7uj

**Comment by chloeatplay** [comment]
:thumbsup: good to close :tada:
