### ISSUE TITLE
Design UI for D8 / M8a, M8b, M8c Discovery Pathway Page, Add badges

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#129]

**Comment by zzzndr** [comment]
Here is the screen for desktop.
Later i will upload the corresponding pages for the mobile layout.

https://redpen.io/8cd2bs

**Comment by zzzndr** [comment]
here is the updated version:
https://redpen.io/h6pmt8

**Comment by zzzndr** [comment]
Here is the updated version where the navigation menu is removed
https://redpen.io/4qmtr2

**Comment by zzzndr** [comment]
Here are updated screens for desktop and mobile:

D8
https://redpen.io/4qmtr2

M8a
https://redpen.io/5p9osr

M8b
https://redpen.io/kpr6m5

M8c
https://redpen.io/8xdvt3

M8d
https://redpen.io/nz36h7

**Comment by zzzndr** [comment]
M8a
https://redpen.io/ok5g4n
New cleaner design with only a hamburger menu

I’ve also updated #127 M9 for us to show this design on a pathway page.

**Comment by zzzndr** [comment]
Here are updated screens for mobile:

M8a
https://redpen.io/vhswc9

M8b
https://redpen.io/8avuf4

M8c
https://redpen.io/ce3sv9

M8d
https://redpen.io/5bwqen

**Comment by chloeatplay** [comment]
:thumbsup: good to close
