### ISSUE TITLE
Design UI for D1 / M1 & D2 / M2 Discovery Landing Page

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#130]
Use visual study as a reference for this per #117

**Comment by zzzndr** [comment]
Here are a few quick experiments how the pathway on the landingpage could be different compared to the badges

https://redpen.io/prjafo

**Comment by zzzndr** [comment]
Here are 2 new versions:

3D qubes for the pathways, flat hexagons for the badges
https://redpen.io/d4pwtc

3 small hexagons for the pathways, 3D hexagons for the badges
https://redpen.io/kya62o

**Comment by zzzndr** [comment]
updated version with lines between the pathway hexagons
https://redpen.io/9qn1o8

**Comment by zzzndr** [comment]
Here are screens for D1 & M1:

The visual in de background of the header is still needs to be refined
The river represents a pathway, at first I can imagine that the badges and story bit icons will be pat of the header image, perhaps later they can be actual badges, loaded at random or most/least popular and real storybit icons

D1
https://redpen.io/qh5bzx

M1 variant 1
https://redpen.io/s4c5fq

m1 variant 2
https://redpen.io/m9veu3

**Comment by zzzndr** [comment]
Here are new screens:

header icon set exploration
https://redpen.io/5tgux7

Desktop v1
https://redpen.io/ge2chf

Desktop v2
https://redpen.io/gwrbv8

Mobile v1
https://redpen.io/y85hpb

Mobile v2
https://redpen.io/z9dtyo

**Comment by zzzndr** [comment]
Here are versions with orange buttons:

Desktop
https://redpen.io/exhpc1

Mobile
https://redpen.io/592oq1

**Comment by zzzndr** [comment]
Here is an updated version with white icons & an orange button
https://redpen.io/kh3t4e

**Comment by zzzndr** [comment]
Here is a screen with an overview of the refined scale levels of the 3 types of headers: landing page, pathway page & badge page. 
https://redpen.io/89ugjo

The clouds, mountains etc are the smallest in the landings page, the biggest in de badge page.

**Comment by zzzndr** [comment]
Here are 2 new variations of the headers for the zoom level concept

The header at the contains only the river, mountains & clouds

The header in the middle contains apart from the, mountains & clouds also some ground clutter like a little flower & 3 dots which give the surface a bit if a texture

The header at the bottom contains hills instead of mountains

with a cloud on header at the bottom
https://redpen.io/swopxh

without a cloud on header at the bottom
https://redpen.io/eugbyn

**Comment by zzzndr** [comment]
Here is a new screen for mobile:
https://redpen.io/mve6pb

Here is a refined variations of the headers for the zoom level concept
https://redpen.io/kvw1xh

**Comment by threeqube** [comment]
I like the zoom concept but with the blue borders, that look like bodies of water, remaining unchanged, the zoom effect diminishes for me. What do you think @zzzndr?

**Comment by zzzndr** [comment]
totally agree with you that the blue borders on both sides diminishes the effect of zooming, I choose to keep them the way they are for the overall balance of the page & to keep the folding effect between the header and the rest of the page (:

When I tried using only green the overal unity between the pages seemed a bit gone for me, but perhaps I'm a bit too carefull (:

Gladly try again to make it work with perhaps a darker shade of green as a border?

**Comment by chloeatplay** [comment]
Agree with comments above. I think the disconnect happens between the first and second screen mainly because of the size of the clouds. Can we take them out completely? Alternatively, instead of having all these different versions, maybe the pathway, badge, dashboard pages are simpler? don't have the header? (edited to explain better what i meant :baby_chick: )

**Comment by zzzndr** [comment]
Here is the sollution we came up with!
nice and plain with a lot more contrast between the 3 zoom levels (:

redpen is taking a brake, so here it is embeded (:

![headers_v5](https://cloud.githubusercontent.com/assets/6721026/2647310/2a9824e4-bf49-11e3-8dde-eff3a074c1b6.jpg)

**Comment by threeqube** [comment]
Looks great! :+1:

**Comment by chloeatplay** [comment]
:thumbsup: from me too :)

**Comment by zzzndr** [comment]
Here are new screens

desktop
https://redpen.io/uqa447bcfc1571942a

mobile
https://redpen.io/ym772018ab12b4b27f

**Comment by zzzndr** [comment]
Here are the logged in screens D2 / M2
Please pay extra attention to the about & FAQ text buttons next to the logo

desktop
https://redpen.io/zn370baeeddb6b7d8d

mobile
https://redpen.io/fm1229b8b46426912d
