### ISSUE TITLE
Design UI for D3 / M3  Discovery Dashboard

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#131]
We can use the QuizUp game and/or RPG games dashboard as a reference for this one.

**Comment by zzzndr** [comment]
Here is a list with possibilties to get started with this page.
I think option A is the least complicated / time consuming?

A) A minimum amount of functionality
- Select 1 pathway from the dashboard page to be highlighted in the header
- Show per category (users own/have wishlisted at least 1 badge of that category) how many badges are earned and/or wishlisted

B) A Bar graph which contains all the pathways with several filters
- The horizontal axis shows the amount of pathways
- The vertical axis can show:
  - percentage completed
  - amount of badges a pathway contains
  - amount of optional badges a pathway contains
  - how long ago a pathway is pledged (oldest is max height)

C) A (curved) line graph which shows the progression of all the pathways over time
- The horizontal axis shows the time
- The vertical axis shows the progression in %
- A line is a pathway which contains:
  - Earned badges
  - Optional badges when they are added (or deleted?) to the pathway 
  - Storybits when they are added (or deleted?) to the pathway

Note of interest: The progression can actually go down without earning badges when optional badges are added to a pathway or can go up when optional badges are deleted from a pathway.

D) A circular star graph
Every point of the star is a category, length is amount of badges earned

here is a link to a pinterest board with samples
http://www.pinterest.com/zzzndr/dashboards/

**Comment by chloeatplay** [comment]
Agreed @zzzndr this is great research and option A seems faster.

**Comment by threeqube** [comment]
:+1:

**Comment by stenington** [comment]
I don't understand the "per category" part of option A.

Also, it may not be hard to get fancy with this page if we use something like [d3](http://d3js.org/) although I'm not sure about feeding it the sort of overall aggregate data it would need. I think the most difficult part of this page is preparing the data, and I don't have a good sense of how easy or difficult that will be right now.

**Comment by zzzndr** [comment]
I understood at first the focus is on healthcare, services & tech? 
So each of these 3 would be a category

Is that possible or does it makes sense?
I'm not completely up to date on this part (:

**Comment by stenington** [comment]
Oh, right! This is probably possible, but the mechanism of determining categories hasn't been established yet, and the easy options won't extend to the full ecosystem well. So there would be a risk that such a feature just wouldn't work on anything but our tightly controlled data.

**Comment by zzzndr** [comment]
okido, thanks for the heads up, we better skip that option for now then  (:

would there be anything else we could show in the dashboard at this point?

**Comment by stenington** [comment]
The first iteration of the dashboard I'll implement probably won't have any meaningful infographic thing in the header, unfortunately. I have #75 open to explore some different possibilities for how to display information, but it's hard to do until we actually know what the data will look like.

**Comment by zzzndr** [comment]
okido (:

**Comment by chloeatplay** [comment]
ah I see the issue, i wonder though if we could surface tags along the lines of # healthcare + # anothertag  . So even if we don't have categories you would be able to surface these main tags. But totally ok to table this for now @stenington

**Comment by zzzndr** [comment]
Here is a very rough sketch of how the dashboard page could be to show the potential?
https://redpen.io/g2ce8r

@chloeatplay @stenington

**Comment by zzzndr** [comment]
Here are 2 screens how the desktop could look like
The background of the header still needs to be refined like the pathway page

variation 1
https://redpen.io/s2yfgp

variation 2
https://redpen.io/xodk4h

**Comment by zzzndr** [comment]
Here is an updated screen for the desktop:
https://redpen.io/4m2sp8

**Comment by zzzndr** [comment]
New versions can be found here:

D3
https://redpen.io/e56xbo

M3 a
https://redpen.io/3zgech

M3 b
https://redpen.io/rkaxj8

M3 c
https://redpen.io/g1ve3y

M3 d
https://redpen.io/27mxr4

**Comment by zzzndr** [comment]
new dashboard desktop screen
https://redpen.io/8m9wh6

**Comment by zzzndr** [comment]
and a new screen (:
https://redpen.io/tp4nr3

**Comment by zzzndr** [comment]
Here are new screens:

Desktop
https://redpen.io/f91d8b

Mobile a
https://redpen.io/ae2p56

Mobile b
https://redpen.io/bq7jz4

Mobile c
https://redpen.io/7918d3

Mobile d
https://redpen.io/3fhz2e

**Comment by zzzndr** [comment]
Here is the updated desktop screen with a refined cleaner header

![03_discovery-pathway-page_dashboard_desktop_v9-01](https://cloud.githubusercontent.com/assets/6721026/2647492/a567b692-bf4b-11e3-9316-834821fbc9de.jpg)

**Comment by zzzndr** [comment]
Here is a new screen with a more centered add pathway icon (:
![03_discovery-pathway-page_dashboard_desktop_v9-2-01](https://cloud.githubusercontent.com/assets/6721026/2650589/7b38eeac-bf75-11e3-8437-e5b66160e0eb.jpg)

**Comment by zzzndr** [comment]
Here are new screens
I swapped the position of badges & favorited, this way favorited applies to badges

desktop
https://redpen.io/vxaf2c1cd63090f557

mobile a
https://redpen.io/cy559d44a1ae3d4df0

mobile b
https://redpen.io/vce5c0a5dad28753a7

mobile c
https://redpen.io/vce5c0a5dad28753a7

**Comment by chloeatplay** [comment]
:thumbsup: fab!
