### ISSUE TITLE
Design UI for D11 /M11 Discovery Badge Page

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#132]

**Comment by zzzndr** [comment]
Here is the screen for the desktop
https://redpen.io/748hwn

To have a consistent look the header is a different variation from the pathway & landing page.
My idea for the header illustration is to have different scale levels for the 3 different pages:

• The current screen for the landingspage has an illustration with a scale level as if you’re looking from the window of a satellite.

• The current screen for the pathway pages has an illustration with a scale level as if you’re looking from the window of a plane.

• The current screen for the badge page has an illustration with a scale level from the perspective of a bird.

**Comment by chloeatplay** [comment]
I like this approach sander!

**Comment by threeqube** [comment]
:+1:

**Comment by zzzndr** [comment]
Here is a refined header illustration for the desktop
https://redpen.io/jrcu3t

Here is the mobile screen
https://redpen.io/crvaof

**Comment by zzzndr** [comment]
here are new screens:

Desktop:
https://redpen.io/cf63zw

Mobile:
https://redpen.io/ud6s2e

**Comment by zzzndr** [comment]
Here are new screens:

Desktop
https://redpen.io/tkz31r

Mobile
https://redpen.io/ar3zq4

**Comment by zzzndr** [comment]
here is a new screen for Desktop:
https://redpen.io/ob94b73344b8f860f9

**Comment by chloeatplay** [comment]
:thumbsup: looks badgelicious !
