### ISSUE TITLE
Design badge visuals top 50

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#135]
@LucasBlair will provide us with art suggestions and content. Would be interesting to incorporate new badgekit studio :dancers: cc @iamjessklein 
Also @chloeatplay can help with this.

**Comment by chloeatplay** [comment]
.@zzzndr will start on the top 50 badges. @LucasBlair will provide the badges that are more or less finalized in the google doc. by coloring them "green" .

**Comment by chloeatplay** [comment]
looks like this is done @zzzndr :tada:

**Comment by zzzndr** [comment]
\o/
