### ISSUE TITLE
Design Pathway End Screen 

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#142]
When you finish a pathway you should get an ending screen. :scream_cat:

**Comment by zzzndr** [comment]
Here is a proposal for the end screen:

In this screen the end screen is a static screen & doesn’t offer functionality to continue or duplicate etc

Desktop
https://redpen.io/cy5da0296916013d46

Mobile
https://redpen.io/frfb5978aa1b41c43a

**Comment by chloeatplay** [comment]
These are great @zzzndr  what if we add a popup with a message in it for completion? Will also add to the transition screen copy, see Point 10 here https://openbadges.etherpad.mozilla.org/discovery-copy

**Comment by zzzndr** [comment]
that makes perfectly sense, working on it!

**Comment by zzzndr** [comment]
desktop a
https://redpen.io/qh7ce03e7313a21d05

desktop b
https://redpen.io/jz76ff23c3be3ef234

**Comment by zzzndr** [comment]
Here are the mobile screens
mobile a
https://redpen.io/dj28e87930e0293911

mobile b
https://redpen.io/hz9fcb21a7a8651248

**Comment by chloeatplay** [comment]
Looks great @zzzndr :thumbsup: we should probably open an implementation ticket for sharing pathway completion :pencil: to self :smile:

**Comment by threeqube** [comment]
Looks beautiful! :+1:
