### ISSUE TITLE
Design illustrations for cross-career badges

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#148]
With the help of @zzzndr 
Reference http://designspiration.net/data/l/766531192643_tF0nth8J_l.jpg
Content in #149

**Comment by chloeatplay** [comment]
First stab at art directing these (upper row is the animals) Lower row how some of these badges might look for other industries ![discovery_badges_art-01](https://cloud.githubusercontent.com/assets/1945209/2619807/a63c6348-bc34-11e3-87f0-131ba8211d31.png)

**Comment by zzzndr** [comment]
These are übercool ((:
So much potential to create badges with this style (:
Really like the bottom-right badge

**Comment by ZeeJab** [comment]
I'M OBSESSED WITH THESE!!

**Comment by threeqube** [comment]
:heart: :+1:

**Comment by zzzndr** [comment]
What I really like about the bottom right badge is that it is basically a clipped illustration of a person wearing a jacket.

I can imagine this principle can work really well for a lot of other situations, for instance I can imagine a clipped version of the bottom left badge with only a few essential elements of the calculator can work really well (:

**Comment by threeqube** [comment]
I also like how you're utilizing the folds to add dimension. :panda_face:

**Comment by iamjessklein** [comment]
I agree with everything everyone wrote before me, these look fantastic @chloeatplay  :baby_chick: 
My only additional bit of feedback:
-  would be to consider that if these are a set, a consistent palette to show the relationship between badges
- the bumble bee badge (second from top left row) stands out to me as a bit different than the others, perhaps it is just a matter of toning down the colors a bit, so it's a shade rather than perfect black.

**Comment by chloeatplay** [comment]
Great points Zoofriends. I updated this to include all the cross career badges 
==> https://redpen.io/qu40d807bc43eb4bc9
Collecting feedback on the above redpen till EOD tomorrow. 
Thanks all :frog: :snail: :snake: :dog: :panda_face: 

cc @LucasBlair @ghami for good measure :pray:

**Comment by LucasBlair** [comment]
Artwork looks great

**Comment by zzzndr** [comment]
looks great indeed!
added a few comments based on what you told us during the stand (:

**Comment by chloeatplay** [comment]
Thanks everyone for great feedback. Iterated and files can be found here if you want to play around/use them https://www.dropbox.com/sh/q1971j65c9c1l5l/O29v3x8K1m Next step would probably be user testing them with some youth to see if they resonate cc @emgollie and take it from there :frog: :cow: :tiger: :elephant: :palm_tree:
