### ISSUE TITLE
Create User testing plan and schedule

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadges-discovery#15]

**Comment by emgollie** [comment]
Might we be able to add this to the agenda for Wednesday's team meeting? Per a conversation with @chloeatplay, our advisory board and HIVE will be highly involved in connecting us with testers. The Youth Radio and Bay Area Video Coalition teens are open to reviewing work as well (my internal recruitment bells are ringing).

@LucasBlair is currently working on a set of personae for Thursday (which I'll be helping with; https://openbadges.etherpad.mozilla.org/pathways-userstories) and I'd like to talk through the broader schedule looking towards May.

**Comment by chloeatplay** [comment]
@emgollie let us know if you need support with this :dancer:

**Comment by iamjessklein** [comment]
@emgollie and I talked about the possibility of piggybacking discovery testing on top of the BadgeKit testing that we have going on.

**Comment by emgollie** [comment]
I talked a stab at the testing plan for the next three weeks: https://openbadges.etherpad.mozilla.org/pathways-userstories. I can write a script with Chloe when she's in town next week too.

@chloeatplay @threeqube, I have a few questions on what we think we'll have ready as far as the UI for the next milestone. Do you mind chiming in on line 20?

**Comment by threeqube** [comment]
> @chloeatplay @threeqube, I have a few questions on what we think we'll have ready as far as the UI for the next milestone. Do you mind chiming in on line 20?

@chloeatplay chimed in. High fidelity testing likely won't be possible until March.

**Comment by emgollie** [comment]
Hi ladies, I have been trying to update the discovery testing plan but realized that I need more details on post-March milestones. Might you be able to tell me more about the outlook after DML (where I'd love us to do discovery testing)? @chloeatplay, if you want to chat for a few minutes tomorrow I'd be happy to--it will just help me better plan towards these milestones:

Jupiter
Saturn
Uranus
Neptune

**Comment by chloeatplay** [comment]
@emgollie sounds great. Here is a demo script https://openbadges.etherpad.mozilla.org/demo-script that we can work from.

**Comment by emgollie** [comment]
Looking forward to discussing the latest iteration of the plan today during the team meeting: https://openbadges.etherpad.mozilla.org/pathways-userstories. I'd love your thoughts on whether the timing matches your development expectations. Thanks @chloeatplay @threeqube @LucasBlair @stenington @ghami.

**Comment by threeqube** [comment]
:+1:

**Comment by chloeatplay** [comment]
:thumbsup: this looks great to me, would move the March 31st milestone to match the Jupiter one (April 12). We can reassess then for the remaining User testing. Happy to create tickets for these @emgollie, just let me know :)

**Comment by emgollie** [comment]
This sounds good, change made @chloeatplay. We can discuss in more detail tomorrow when we meet to discuss with @threeqube.

**Comment by chloeatplay** [comment]
@emgollie @threeqube should we close this ticket? I believe Emily has created the user testing plan already.

**Comment by threeqube** [comment]
Will defer to @emgollie.

**Comment by emgollie** [comment]
Yes, closing and opening an implementation ticket. Thanks!
