### ISSUE TITLE
Make pledged pathway details editable

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#154]
The pathway name and description should be editable for a pledged pathway.

For more info see discussion in #62.

**Comment by shiba4life** [comment]
I'm going to start working on this issue.

**Comment by chloeatplay** [comment]
Reassigning to @tomtang539 now officially on this repo :tada: :smile_cat:

**Comment by shiba4life** [comment]
I think we can mark this as closed?

**Comment by chloeatplay** [comment]
:thumbsup:
