### ISSUE TITLE
Create edit mode for storybits after they have been created

### ISSUE THREAD

**Issue by zzzndr** [mozilla/openbadges-discovery#159]
@chloeatplay @stenington

**Comment by stenington** [comment]
@zzzndr Can you say a little more about what this ticket entails?

**Comment by zzzndr** [comment]
@stenington after you have added a storybit there is no way to edit the content of the storybit. we haven't created wireframes for this functionality

I know I would make a ton of typo's, so editing would be great!

**Comment by stenington** [comment]
Ooooooh, yep. I can see that as a problem. :)

**Comment by stenington** [comment]
I think the code portions of this really wrap into #79 and #80 which are set for the next milestone after this one, so I'm just taking the "Code" tag off this and considering it a design ticket.

**Comment by chloeatplay** [comment]
:thumbsup: I will reassign to me as a UX ticket

**Comment by zzzndr** [comment]
The idea is that the name add storybit’ button in de navigation menu becomes ’storybit’

I’ve slightly rephrased the text above the pathway because the idea is to give the storybit mode 2 functionalities

desktop a
https://redpen.io/ua0cb737e2f3c039a0
The user has already clicked on the pathway to place a storybit, dragging the new storybit will reposition it. If an existing storybit is clicked we go to screen b

desktop b
https://redpen.io/ay01df3b2a89ea34fb

the mobile screens will follow shortly

**Comment by zzzndr** [comment]
here are new screens with a proper cogwheel icon (:

desktop a
https://redpen.io/ym9fc8c01692eaf30c

desktop b
https://redpen.io/cte48b61bcd1d97ba5

**Comment by chloeatplay** [comment]
Looks great :thumbsup: closing and connecting to #26
