### ISSUE TITLE
Create user personas

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadges-discovery#16]
cc/ @LucasBlair

**Comment by emgollie** [comment]
We have a meeting with Grainne and An-Me on Thursday for @LucasBlair to talk through V1 (though we'll likely discuss on the team call too). Per our conversation today, we think this will help potential partners more quickly visualize the learners we're designing with.

cc @chloeatplay

**Comment by chloeatplay** [comment]
Reassigning this to @LucasBlair

**Comment by chloeatplay** [comment]
@LucasBlair  user personas are complete correct? Can you create a wiki page for them? Then I can close the ticket. Thanks! :balloon:
