### ISSUE TITLE
User Test Quiz

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#162]
@emgollie will user test quiz so we can improve and iterate on cc @chloeatplay @ghami

**Comment by emgollie** [comment]
Drafting updated testing plan here: https://openbadges.etherpad.mozilla.org/pathways-userstories

If we reach out to the teens we suggested in the discovery meeting a few weeks ago, I think we'll be able to hit the goal of 30 respondents within a few days. I'm making a few language suggestions to the quiz so we can begin distribution. cc @threeqube @LucasBlair

**Comment by threeqube** [comment]
Plan looks good to me! :+1:

**Comment by LucasBlair** [comment]
Looks good. I added another opportunity to connect with students (Randolph High School Option II) I met the director at the Summit.

**Comment by emgollie** [comment]
Thanks @LucasBlair. @chloeatplay, I added a few thoughts on language in that pad--if you are good with changes, I think we can start getting people to the quiz.

**Comment by chloeatplay** [comment]
This is now updated, @emgollie let's start distributing per your plan.

**Comment by chloeatplay** [comment]
Moving this to Saturn :stars:

**Comment by emgollie** [comment]
Testing implementation bug is https://github.com/mozilla/openbadges-discovery/issues/182. Thanks!
