### ISSUE TITLE
pathway editing undo

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#167]
It looks like there might be some drop-in undo libraries like http://backbone.undojs.com/ that might make adding undo quite easy, if that's preferable to the "Are you sure?"-style dialogs.

**Comment by chloeatplay** [comment]
yAh!! Undo is much better than are you sure :pray:

**Comment by chloeatplay** [comment]
I saw this being implemented :eyes: should we close?

**Comment by stenington** [comment]
Oh, sure. Undo is doable.
