### ISSUE TITLE
Implement the ui for the Pathway Landing D4/M4 

### ISSUE THREAD

**Issue by ZeeJab** [mozilla/openbadges-discovery#169]
Refer to https://github.com/mozilla/openbadges-discovery/wiki/Discovery-Pathway-UI-Design#d4--m4

**Comment by shiba4life** [comment]
@ZeeJab Are you still working on this issue?  We've taken a stab at this, here's how it looks right now:
https://redpen.io/sd574c5546ba26a9ef
