### ISSUE TITLE
Create advisory board

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadges-discovery#17]

**Comment by emgollie** [comment]
Discussed today with @chloeatplay + am excited for this! Have outlined some thoughts here: https://openbadges.etherpad.mozilla.org/discovery-advisory-board

@threeqube @chloeatplay Would you mind explaining the milestones to me (i.e. the difference between earth and Mars)?

**Comment by threeqube** [comment]
@emgollie Happy to schedule time to go over the milestones. In the mean time, updated version viewable here: https://openbadges.etherpad.mozilla.org/discovery-milestones

**Comment by emgollie** [comment]
This is helpful, thanks. @chloeatplay, let me know what you think about the very rough board plans and we can add to the prospective invitee list.

**Comment by chloeatplay** [comment]
Initial list looks great, thanks Emily!! Added some thoughts. Lets have people give input at weekly call (I remember some names came up there too), and meanwhile move forward with invites to the ones we already know we want to get involved.

**Comment by threeqube** [comment]
:+1:

**Comment by emgollie** [comment]
Sounds good, thanks you two. I'd love to spend 5-10 minutes on this tomorrow if your agenda allows and then start sending invites.

**Comment by chloeatplay** [comment]
sounds great :thumbsup:

**Comment by threeqube** [comment]
:+1:

**Comment by chloeatplay** [comment]
Update on this: Me and An-Me have concluded on a tier 1 advisory board of 5-6 people. An-Me will do outreach this week and check in with Robert for input. The expectation is that of 2 conference calls to gather feedback an possibly an in person meeting at the end of the project, budget allowing. Once we have advisory confirmed we will also add them to the splash page #13

**Comment by chloeatplay** [comment]
This is done :+1:

**Comment by threeqube** [comment]
Bravo!
