### ISSUE TITLE
Create first version of site copy 

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#176]
cc @threeqube @SueSmith 
Starting this here https://openbadges.etherpad.mozilla.org/discovery-copy 

:pencil: :pencil2: :panda_face:

**Comment by SueSmith** [comment]
Hi @chloeatplay - great! I see you've started an intro paragraph in there - do you have other sections you're particularly looking for copy on at the moment or should I go by the latest designs?

**Comment by threeqube** [comment]
@SueSmith I thinking going by latest designs would work best. @zzzndr is aggregating them here: https://github.com/mozilla/openbadges-discovery/wiki/Discovery-Pathway-UI-Design

**Comment by SueSmith** [comment]
Thanks @threeqube 

Added a few more bits to the etherpad - give me a shout :loudspeaker: if I can do any more whenever @chloeatplay

**Comment by threeqube** [comment]
:+1:

**Comment by chloeatplay** [comment]
@SueSmith thanks so much. Added some clarifications. If you and @threeqube want to take one more look I can close this issue for now and move to implementation.

**Comment by SueSmith** [comment]
@chloeatplay everything looks good to me! 

Let me know if I can help e.g. if you want a written tutorial like the one we have for BadgeKit users https://github.com/mozilla/openbadges-badgekit/wiki/BadgeKit-Tutorial

**Comment by chloeatplay** [comment]
That would be amazing. I will open a ticket so we can tackle that once we are closer to launch :+1:

**Comment by threeqube** [comment]
:+1:
