### ISSUE TITLE
Create transition screens

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#177]
Create screens for transitions between actions on the interface. Starting to write these down here: https://openbadges.etherpad.mozilla.org/discovery-copy

**Comment by chloeatplay** [comment]
@SueSmith can you take a final look under line 77 for these? much thanks :pray:

**Comment by SueSmith** [comment]
@chloeatplay Looks good! Made a couple of tiny edits, am on my phone so hope it hasn't messed the etherpad up at all..

**Comment by chloeatplay** [comment]
Thanks @SueSmith :+1:
