### ISSUE TITLE
Design transition screens

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#178]
Connected to #177 Imagining these as popup screens that give you helpful messages as you progress through the interface. @zzzndr want to take a stab at designing them?

**Comment by zzzndr** [comment]
sure!

**Comment by threeqube** [comment]
Are these like tooltips?

**Comment by chloeatplay** [comment]
@threeqube I think we can explore both tooltips and transition screens (i.e. pop-ups)

**Comment by threeqube** [comment]
:+1: sounds good to me!

**Comment by chloeatplay** [comment]
no longer in scope for May launch.
