### ISSUE TITLE
Render a re-arrangeable pathway grid

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#18]
Work out the rendering of a re-arrangeable pathway grid. The rest of the page will be dealt with in another ticket. 

I think the pathway being re-arrangeable has the greatest impact on how the templates will look, so may as well do that up front and then limit it to having clicked the rearrange button later.

Note that badges in a pathway can be made mandatory, which simply means they cannot be deleted from the pathway. This is not accessible through the UI but can be set in the database.

**Comment by stenington** [comment]
I've begun to explore the UI here: http://openbadges-discovery.herokuapp.com

Still need to investigate mobile though, which doesn't seem to have any support for HTML5 drag and drop.

**Comment by threeqube** [comment]
so cool @stenington :+1:

**Comment by stenington** [comment]
Looks like HTML5 drag and drop doesn't work in any mobile browsers, but jquery ui + jquery ui touch punch does (at least on my iphone). Check out http://openbadges-discovery.herokuapp.com on a mobile device!

**Comment by threeqube** [comment]
It also does on my iphone 5S! Very cool! :dancer: :koala:

**Comment by stenington** [comment]
I think #31 is good enough to satisfy this. The only annoyance is that all users are editing a shared pathway instead of having their own clones, but I think adding in the pathway cloning belongs in another ticket. I'm going to solicit some code reviews and close this out.

**Comment by threeqube** [comment]
:+1:
