### ISSUE TITLE
Quiz testing: Launching in-person

### ISSUE THREAD

**Issue by emgollie** [mozilla/openbadges-discovery#182]
Per https://github.com/mozilla/openbadges-discovery/issues/15, we're nearly ready to start testing the quiz in-person. From our plan (https://openbadges.etherpad.mozilla.org/pathways-userstories), we're eager to get this in front of 30 relevant teens in the next week and a half.

Next steps are for @ghami and I to discuss tactical testing processes and for me to proofread the quiz. cc @ghami @LucasBlair @threeqube @chloeatplay

**Comment by emgollie** [comment]
@ghami, @chloeatplay and I discussed today. We got interesting feedback from a community member at the University of Michigan that we can continue to consider as we test. 

The quiz has been copy edited, and if each of us can identify ~5 teens to test with next week, that would be wonderful. On Monday's team call we can discuss best practices for live interviewing. cc @threeqube @LucasBlair

**Comment by emgollie** [comment]
Eek: I talked to Bay Area Video Coalition about coming into test and they said their students are currently heads down finishing final projects in April. Considering other after school testing opportunities.

**Comment by emgollie** [comment]
BAVC agreed to review the quiz and possibly send it along to students. I created this short link if you'd like to repurpose it: http://bit.ly/1qEBMYp

I know that @ghami mentioned concerns with local student breaks, and has anyone else had success prepping to share this with teens near them? @LucasBlair @threeqube @chloeatplay

**Comment by LucasBlair** [comment]
I will circle back with the school in Jersey.

**Comment by chloeatplay** [comment]
@LucasBlair reminder we are looking for f2f interactions/ user research, given the missing functionality, the quiz is not in a position to allow stand-alone testing atm.

**Comment by emgollie** [comment]
@LucasBlair @chloeatplay @ghami Knowing that in-person testing for it may be difficult, we can also plan remote walk-thrus as needed. We'll be able to share prototypes soon too!

**Comment by LucasBlair** [comment]
I will also reach out to connections in Pittsburgh in Philly. Those will be easier to do in person.

**Comment by emgollie** [comment]
:+1: Thanks @LucasBlair!

**Comment by threeqube** [comment]
Might be stating something you've already considered and thought of before but what about Hive?

**Comment by emgollie** [comment]
Yes, and... :)

I'm wary of barraging them every month as we recently tested BadgeKit with them and may want to again soon. I'd prefer to have our asks of Hive be for in-depth, in-person tests (AKA more detailed engagements than this quick quiz). Thanks for asking @threeqube!

**Comment by threeqube** [comment]
Of course you've thought about this. Thanks @emgollie! :koala:

**Comment by ghami** [comment]
Unfortunately the teens I had hoped to test with over the holidays are no
longer able to do so.

**Comment by chloeatplay** [comment]
this is done
