### ISSUE TITLE
Code style consistency

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#187]
It would be nice to ensure some basic things like tabs v. spaces and indent depth in the project, not so much for visually consistency or nit-pickiness, but to avoid small changes made with aggressive editors from then including 500 whitespace diffs or whatever.

Adding a validation step to the precommit-hooks might do the trick.

**Comment by ZeeJab** [comment]
:+1:

**Comment by stenington** [comment]
@ZeeJab any favorite tools you already use?

`precommit-hook` runs jshint, which might have some config we could tweak at least for .js files. There's also jslint, though it's super verbose.

Tidying templates can be tricky because they're templates, not properly formed HTML. Maybe there's a trick to prerender and then lint or something.

**Comment by ZeeJab** [comment]
hmm, build step with the ci? jslint is for sure verbose, we can configure it?
There's also js beautify to fix in a grunt task maybe? 

Pre commit hooks are hard to enforce tho, since they exist outside the repo?

**Comment by stenington** [comment]
The project is using https://github.com/nlf/precommit-hook right now, which runs tests, runs jshint, and lets you specify additional "validation" scripts to run before allowing a commit. jshint is configurable through .jshintrc and .jshintignore files, although I still haven't fully gotten the hang of how .jshintrc files in different directories interact with each other.

jslint offers similar config options I think, although I feel like to start I'd probably turn off like 99% of what it complains about. It's super whiny.

js-beautify could be cool, too. I was looking at that yesterday evening and it seems like it might be a good addition.

**Comment by stenington** [comment]
Closing out for now, can open new issues to address specifics if necessary
