### ISSUE TITLE
Design UI for Editing Pathway Name & Dropping Out of a Pathway

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#193]

**Comment by zzzndr** [comment]
Here is an enhanced pathway settings popup with the option to drop out of a pledged pathway. I tried to make the button to do so unobtrusive.

Pathway settings a
https://redpen.io/tg9a324b3246a1bcda

Clicking on the (x) right of the ‘Pledged’  will lead you to screen b

Pathway settings b
https://redpen.io/vkf85d3005a271f852

**Comment by chloeatplay** [comment]
Looks great Sander! Will close this :+1:
