### ISSUE TITLE
Design layout for About & FAQ Pages

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#198]

**Comment by chloeatplay** [comment]
Hey https://redpen.io/bmbcb61c073f770a5b these look good, but lets make them SUPER SIMPLE, as in one page with text. Can you use the text from here to design them? https://openbadges.etherpad.mozilla.org/discovery-copy

thanks! :pray:

**Comment by zzzndr** [comment]
Here are new screens for the About & FAQ page (:
Both screens are single column designs

About page
https://redpen.io/zk9a30f1105289b3a8

FAQ page
https://redpen.io/md81728c775d162b98

**Comment by threeqube** [comment]
:+1:

**Comment by chloeatplay** [comment]
@zzzndr let's drop the advisory group images :+1: We can just add their names for now, it looks ackward within this setting- unless we create a new page "advisory group which we are not doing for now :page_facing_up: :no_entry_sign:
