### ISSUE TITLE
site property: where does this discovery tool live?

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadges-discovery#2]
Will it be discovery.badgekit.org?

**Comment by iamjessklein** [comment]
The last time that I discussed this with @chloeatplay it was still in discussion with Gates about where this should live. It seems a bit too niche to put at discovery.badgekit.org based on my understanding of the project scope. I would eventually put the work that we iterate on for badgekit (with the badgekit specific lens) in the discovery url, however, I suspect that there is going to be a non-badgekit url required for this iteration. 

@chloeatplay thoughts on this?

**Comment by threeqube** [comment]
I tend to agree. The scope of Gates discovery is quite specific at least in this first iteration of it.

**Comment by cmcavoy** [comment]
i vote for discovery.openbadges.org

**Comment by chloeatplay** [comment]
What everyone else said. ==> @cmcavoy :+1:  discovery.openbadges.org

**Comment by threeqube** [comment]
Works for me too. :+1:

**Comment by iamjessklein** [comment]
I think that works for this prototype.

**Comment by threeqube** [comment]
Wait before we close this @cmcavoy who's on it to make sure discoery.openbadges.org instance is stood up?
