### ISSUE TITLE
Dashboard accordion widget

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#200]
@zzzndr @chloeatplay If you go to http://openbadges-discovery.herokuapp.com, log in and go to the dashboard, I wonder if you find how the accordion works a bit odd. It starts with all panels open, but then as you click the headers it's only ever possible to have a single panel open after that. 

My gut says on mobile it should start with only a single panel open, and only allow a single panel to be open, while on desktop I'm not sure I see much point in collapsing the panels at all. But if you're happy with how it is then I am too.

**Comment by zzzndr** [comment]
agree that it feels odd on desktop
the idea is that the accordion only works on mobile with only the pathway opened by default

if you go to the wiki you see an example (:
https://github.com/mozilla/openbadges-discovery/wiki/Discovery-Pathway-UI-Design#d3--m3

**Comment by malynda** [comment]
@stenington @zzzndr @chloeatplay This is now changed to a non-accordion layout for the desktop, and will be included in our PR for #190

**Comment by chloeatplay** [comment]
:+1: thanks @mchizek
