### ISSUE TITLE
Change button classes to match Foundation conventions

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#216]
Foundation uses these basic button classes: http://foundation.zurb.com/docs/components/buttons.html#advanced
- `button` for primary buttons
- `button secondary` for secondary
- `button success`
- `button alert`

I think we may as well follow suit if we can.

**Comment by shiba4life** [comment]
Working on this one.

**Comment by shiba4life** [comment]
Implemented.  Note that we don't have a button success (green).
