### ISSUE TITLE
Make buttons responsive

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#222]
See https://github.com/mozilla/openbadges-discovery/pull/213#discussion_r11821513

**Comment by malynda** [comment]
Could someone clarify this issue? Was it re: the text piling up as seen in the linked comment or are button sizes supposed to change?

**Comment by zzzndr** [comment]
for now i would focus on fixing the piling up of the text (:
the button sizes are supposed to change a bit as well but that is a really minor issue, not worth it atm i think (:

**Comment by ZeeJab** [comment]
@malynda && @zzzndr I've fixed this in my PR.

**Comment by zzzndr** [comment]
cool!
