### ISSUE TITLE
Adjust user panel

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#223]
As per https://github.com/mozilla/openbadges-discovery/pull/213#discussion_r11821643

**Comment by malynda** [comment]
Clarification?

**Comment by threeqube** [comment]
If you click on that comment link, provides more context but has to do with the following image:

![screen shot 2014-04-21 at 3 18 25 pm](https://cloud.githubusercontent.com/assets/1824988/2757889/c086dc30-c989-11e3-84b4-8cabc0d4f2c2.png)

**Comment by zzzndr** [comment]
apart from that i'll change the header visual so the avatar will never overlap a badge / storybit icon!

**Comment by ZeeJab** [comment]
@malynda && @threeqube && @zzzndr this was also done in my PR and is reflected in master atm.

**Comment by zzzndr** [comment]
yay (:

**Comment by threeqube** [comment]
:hammer: :+1:
