### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#227]
1) Landing page:

*Hamburger menu :
         -dimensions should be 40px x 30px and a rollover colour of orange (#f8933c) instead of blue
*Login button:
    - button is too narrow, text is taking 2 lines
    - button should be 240px wide
    - we need the font awesome ‘double arrow’ to the right of the text 
      http://tinyurl.com/luvb47q
    - there seems to be a hint of dark blue between the orange of the button and the white border colour?
*Text
The text and the button belong together, if there is less text compared to the screen dump, the best is this solution:
    - The text should be left aligned 
    - There needs to be a margin of 40px between the text & the button
    - The position of the text & button should together be centered
    - Can you use a bottom margin of 20px instead of 30px so there is more distance between the button and the header illustration?

Tablet View: redpen corrections
https://redpen.io/gvbe76faf89894c38d

Smartphone view: redpen corrections
https://redpen.io/qm874694931577560e

*Body- 
Check out the redpen for notes on the dimensions. 
https://redpen.io/kn6a8fa0bfff0b912b

2) Badge page:

*Header:
The Margins description below header visual should be:
    top margin between title & header visual: 60px
    top margin between heart icon & header visual: 50px or -10px of title.
    top margin between description & title: 30px
    top margin between tags & description: 30px
    bottom margin between tags & bottom body: 60px

Check out the dekstop redpen for notes
https://redpen.io/kr3bdb78f912260b60

*Text:

Title: Open Sans Light, font-size: 32px, color: #4d4f53
 Description: Open Sans Regular, font-size: 16px, color: #4d4f53, leading: 22px
Favorited heart icon: Font-size: 25px, color: #0fa1d6
The favorite icon should be positioned to the left of the title

*Bug, in tablet & smartphone mode the icon snaps to the left of the screen, should behave the same way as in desktop view. 

Check out the tablet redpen for notes
https://redpen.io/gvbe76faf89894c38d

Here is the smartphone redpen for notes
https://redpen.io/dz2877257b4fee3eb0

*Background visual

Please use the smartphone background visual in smartphone view badgesHeaderMobile.svg in dropbox.

3) Dashboard page
*Header
The avatar + text in the top right can be removed on this page
The big avatar icon needs to be centered horizontally

*Text
Name:
Open Sans Regular, font-size: 24px
top margin with avatar is 25px

Text pathways, badges & favorited:
Open Sans Regular, font-size: 14px
Please use capitals: Pathways, Badges & Favorited, my bad, forgot to do that in the screendumps.
The icons & text should always remain on the same line.

Check out the dekstop redpen for notes
https://redpen.io/do97cb2bdf54458823

Check out the tablet redpen for notes
https://redpen.io/koe693b17427c19a51

Here is the smartphone redpen for notes
https://redpen.io/ge1307e0d8aa16e22c

*Background visual
Please use the smartphone background visual in smartphone view dashboardHeaderMobile.svg in dropbox.

**Comment by chloeatplay** [comment]
cc @zzzndr @ZeeJab

**Comment by ZeeJab** [comment]
I can work on these this afternoon :-)
