### ISSUE TITLE
Differently heighted items in Foundation grid

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#235]
HumanView provides a nice helper for rendering a collection into a container that's being used to render badges and pathways into the listing page, resulting in a structure somewhat like:

``` html
<div class="row">
  <div class="item large-4 columns">...</div>
  <div class="item large-4 columns">...</div>
  ... many more
  <div class="item large-4 columns">...</div>
</div>
```

Unfortunately, due to the items being differently heighted because of title length or number of tags, this can result in float problems as shown below:

![screen shot 2014-04-23 at 5 14 53 pm](https://cloud.githubusercontent.com/assets/55319/2783425/f53f98a0-cb2c-11e3-8547-d36f290bcff2.png)

Because the 4th item in the top row is shorter than the 3rd, the next row can't float left to form a full row of 4.

The short-term hack in https://github.com/mozilla/openbadges-discovery/commit/143021e381f4c97aa2fddd0c21334a3462e5ec25#diff-413d920350a7c1bdb5631997e1ca9865R5 sets a fixed height and hides overflow, which evens out the rows but obviously doesn't work well for the taller columns which get clipped.

There are at least three possible ways to solve this: 

1) try out Foundation's [block grid](http://foundation.zurb.com/docs/v/4.3.2/components/block-grid.html)
2) find a way to make items even heights
3) implement a more involved collection rendering scheme that sets each group of 4 items inside their own row

I can't immediately think of how to do 2 without javascript, which seems lame, and 3 makes it tricky to add/remove items without a full re-render which isn't ideal.

**Comment by ZeeJab** [comment]
We could use masonry.js
We're using it in badgekit and it works great

**Comment by stenington** [comment]
Ah, yeah, masonry could work as an alternative, assuming that brick-stacking style is okay with the designers!
