### ISSUE TITLE
Insert Sample Pathway Info to Demo

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#236]
There are two complete pathways in the excel doc

1st: Mozilla Engineer Tools Intern lines 2-17
2nd: Mozilla User Experience Intern lines 18-33

cc/ @LucasBlair 

@zzzndr can you provide the art you designed for these two pathways in a dropfox link format for @stenington 

grazie!

**Comment by stenington** [comment]
We're adding two columns to the spreadsheet: pathway name and pathway description. For "Pathway X", the name "Pathway X" should appear in the pathway name column for EVERY badge it contains. The description for "Pathway X" just needs to appear once in ANY of the badge rows in that pathway. Similarly, a link to the artwork for the pathway can appear once in ANY of the badge rows in that pathway in a new column named something like "pathway image".

**Comment by chloeatplay** [comment]
:thumbsup:

**Comment by zzzndr** [comment]
voila!
https://www.dropbox.com/s/1gq0oso1g4pvkof/mozillaDeveloperToolsEngineer.svg
https://www.dropbox.com/s/q18gczwgpi8fpf8/mozillaInternUXdesigner.svg

**Comment by threeqube** [comment]
:+1:

**Comment by stenington** [comment]
Okay, doing it a little differently than above. Define pathway data like title and description etc. in the tab named Pathways. For each badge in that pathway, paste the pathway name in the "Pathway name" column on the relevant badge sheet. Also, don't rename the Pathways tab or everything will break.

**Comment by chloeatplay** [comment]
Got it! cc @LucasBlair @zzzndr folks this :point_up: as an FYI

**Comment by zzzndr** [comment]
got it!

**Comment by LucasBlair** [comment]
roger

**Comment by stenington** [comment]
@LucasBlair These are the new rules that I have just made up.

Mikebot skips all badge rows with an empty cell in the **Keeping?** column. To keep a badge, just put anything at all in that column. (Color won't work though, mikebot is apparently colorblind.)

To add a badge to multiple pathways, just list the pathway names of all the pathways it belongs to in the **Pathway name** column, separated by a comma. That means pathway names cannot have commas in them, though. I don't think that should be an issue.

**Comment by stenington** [comment]
Also you can force a refresh of the data with `<instance url>/api/mikebot/activate`, e.g. http://discovery-234.herokuapp.com/api/mikebot/activate. It will show you a json dump of the data it imported.

**Comment by stenington** [comment]
Uh, note that hitting the above url **will** lose any pledged pathways...

**Comment by LucasBlair** [comment]
Sounds good Mike. Thanks for the update. As @chloeatplay and @zzzndr claim badge art assignments they will fill out that column with S's and C's. In the mean time I will add something in all the green cells.

All hail Mikebot

**Comment by jpcamara** [comment]
I, for one, welcome our new mikebot overlords
