### ISSUE TITLE
Update Site With New Smashing Logo

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#237]
The dapper @adiladiladil has created a new logo for us. Find it over here https://www.dropbox.com/s/55b6g2hjoqmzpm5/Discover%20Logo-01.svg

**Comment by threeqube** [comment]
Yay! :+1:

**Comment by zzzndr** [comment]
cool! 
hopefully i'll be able to see it eventually when dropbox decides it's time finish loading (:

**Comment by zzzndr** [comment]
the logo is gorgeous (:

**Comment by ZeeJab** [comment]
oh so its not just mine that's taking forever to load... i gave up after 3 min :-p

**Comment by ZeeJab** [comment]
im gonna take it upon myself to add the logo in between the ui changes i'm making. just fyi.

**Comment by zzzndr** [comment]
in my case it took only 2 hours, not bad i say!

**Comment by threeqube** [comment]
:+1:
