### ISSUE TITLE
Build the listing page

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#24]
The listing page is basically a view on a combo of directory and pathways data. Data will have to be fetched from each and collated in some fashion.

This should include filters, or if not then that should become an additional ticket.

**Comment by threeqube** [comment]
> This should include filters, or if not then that should become an additional ticket. 

:+1: on filters. What do you mean by "if not then that should become an additional ticket"?

**Comment by stenington** [comment]
If it turns out to be easiest to build the page without filters first, we could then close this ticket and open a new one to track adding the filters. Sometimes it's nicer to break things down that way if needed, but I have a feeling they can be done in a single ticket.

I think long-lived implementation tickets with too much discussion or too many commits get hard to deal with though.

**Comment by threeqube** [comment]
Got it. Sounds good to me.

**Comment by stenington** [comment]
Replaced by more detailed tickets.
