### ISSUE TITLE
Image proxying/canvas image security warning

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#240]
Looks like we need to proxy images for use in canvas or they run into security restrictions that prevent accessing pixel data. I'm actually not 100% sure why we're accessing pixel data... it seems to have something to do with mouse events and maybe click detection?

If we can prevent EaselJS from accessing pixel data that might work too instead of proxying.

**Comment by cmcavoy** [comment]
Talk to @brianloveswords about this...he ran into a similar issue using
Fabric.js. I think you're right, proxying is the solution, but...run it by
him too.

**Comment by brianloveswords** [comment]
So any image data you pull in needs to follow Same-Origin Policy (or be CORS enabled) or else you end up "tainting" the canvas: https://developer.mozilla.org/en-US/docs/HTML/CORS_Enabled_Image.

If you can't guarantee that, you will have to proxy the image data.
