### ISSUE TITLE
Never-ending scroll & the back button

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#242]
It makes me sad that if I click "View more" 20 times, then click a badge way down the list to see the details, then click Back to return to the listing view that I only get 8 badges. Viewing more should probably adjust a query parameter or something that specifies how many badges to initially show. I think that would allow the back button to load the previously shown number of badges right off the bat.

**Comment by threeqube** [comment]
Don't be :crying_cat_face: @stenington
