### ISSUE TITLE
Better Header with proper Hambuger links

### ISSUE THREAD

**Issue by shiba4life** [mozilla/openbadges-discovery#248]
![screen shot 2014-04-30 at 11 03 23 am](https://cloud.githubusercontent.com/assets/4220945/2842829/a4cc6dca-d078-11e3-8211-34d172d3055b.png)

Kind of like this.

**Comment by chloeatplay** [comment]
:+1: :tada: yes!

**Comment by zzzndr** [comment]
sounds like a plan!
if you need help with measurements...

**Comment by malynda** [comment]
yes, please @zzzndr! What are the search bar dimensions?

**Comment by zzzndr** [comment]
here are the dimensions:
https://redpen.io/gq86b7172b70903b0b

**Comment by malynda** [comment]
Thanks!

**Comment by malynda** [comment]
Almost there! https://www.dropbox.com/s/a28v35znvsrma2l/Screenshot%202014-05-01%2014.54.14.png

**Comment by zzzndr** [comment]
nice!

**Comment by malynda** [comment]
https://www.dropbox.com/s/4g85ojj0sqgx8w9/Screenshot%202014-05-01%2015.37.27.png

**Comment by zzzndr** [comment]
looks good!

**Comment by chloeatplay** [comment]
one nitty picky thing: we also need #webliteracy

**Comment by stenington** [comment]
Yep, kicked #295 back to "working" status to track that.
