### ISSUE TITLE
Poor internet connectivity demo scenario

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#251]
Thinking forward to demoing this, I wonder if @chloeatplay wants any backup measures in place to be able to demo this completely offline? Right now poor internet connectivity means a slow or entirely unresponsive app, unfortunately, due to several resources being loaded externally.

**Comment by chloeatplay** [comment]
@stenington yes those would be nice, could be styled blue. Let me know and I can provide css guidelines.
