### ISSUE TITLE
Mock login for demo

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#252]
Just have mock login that doesn't rely on an external service for the demo

**Comment by stenington** [comment]
The mock could also show name instead of email, etc.

**Comment by stenington** [comment]
@chloeatplay I can think of a few different ways to do this and I'm curious how you're picturing it in your head.

At one end of the spectrum, mock login could simply pop up a dialog when you press the login button asking you to enter your email address, and that's it. That would keep things very close to Persona, but without the external dependency.

At the other end of the spectrum, we could invent a user and have a profile picture, full name, etc. for them, and when you click the login button, it immediately makes it look like you're logged in as that person. This might paint a prettier picture, but it's probably a bit farther from reality if that matters. Also, in that scenario having many people look at the app simultaneously might not work because they could be simultaneously editing the same pathway, for example.

There may be some middle-ground solutions as well. Which features are the most important for the demo?

**Comment by chloeatplay** [comment]
I was thinking more of the second option, can provide the profile picture full name etc.

**Comment by stenington** [comment]
@chloeatplay Ok, do you think it will be a problem to have multiple people logged in as the same user? Another option could be to show people the same name, avatar etc. but under the hood give them different user ids or something.

**Comment by chloeatplay** [comment]
Hmm, let;s re-evaluate here. Since this will be used for 1 case, demoing to R. wondering if we should scratch it all together since it looks more complicated than I thought originally.

**Comment by stenington** [comment]
Ok, well I'll just start with something very simple to get us started and we can add detail if there's time.

**Comment by chloeatplay** [comment]
:musical_note: to my :ear: s
