### ISSUE TITLE
New badges should appear at the top of a pathway

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#253]

**Comment by stenington** [comment]
@chloeatplay We could also fake this by building a pathway that leaves the top row empty, depending on requirements. If you want to add 10 badges that won't work, but if you just want to add 1 or 2 it might be fine?

**Comment by chloeatplay** [comment]
ah, indeed! Let's fake it then :black_joker:

**Comment by stenington** [comment]
Okay. Not closing this because it's not fixed, but I'll take it off the Ready queue.
