### ISSUE TITLE
accordion should begin all open, and then be individually togglable

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#256]
which is not the Foundation default, I think.

**Comment by stenington** [comment]
@chloeatplay @zzzndr The UI designs seem to indicate that on desktop there's no accordioning at all, but it appears for mobile. Is that still what we want, or should both have individually toggleable sections?

**Comment by chloeatplay** [comment]
I defer to @zzzndr

**Comment by zzzndr** [comment]
the design is to have no accordion function at all on desktop, only on mobile (:

but if having an accordion function for both desktop & mobile is the least time consuming, i would go for that at this stage (:

**Comment by chloeatplay** [comment]
For the demo I would go with both of them being open when you first visit the page then :)

**Comment by zzzndr** [comment]
sounds like a plan to me!
