### ISSUE TITLE
Insert fake data for backpack/earned section

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#258]

**Comment by stenington** [comment]
Any particular badges you'd want marked as earned? Should I just randomly choose some from the spreadsheet?

**Comment by chloeatplay** [comment]
Hmm- lets have @LucasBlair weigh on this. Depends on the pathways we demo.

**Comment by LucasBlair** [comment]
All of the tech badges we will demo are earned badges. We didn't start asking people about their goals (unearned badges) until after those interviews were completed. The eldercare pathway is all earned badges as well. The remaining healthcare  and service pathways are not from interviews so they can be marked randomly if you want to demonstrate the distinction between earned and unearned.

**Comment by chloeatplay** [comment]
Hey @LucasBlair i think we have a different understanding of "earned" in this context. The demo will be done from the POV of a user, not the people who submitted their pathways. Therefore, can you think which pathways you want to demo and we can show some badges as "earned" in the backpack for that user.

**Comment by stenington** [comment]
Decision on this was to actually show badges from the Backpack. 

Backup plan is to drop the "earned badges" concept as too confusing to explain a fake version for the demo.

**Comment by stenington** [comment]
![screen shot 2014-05-14 at 5 27 35 pm](https://cloud.githubusercontent.com/assets/55319/2977713/9e6a2a12-dbae-11e3-866b-15e7e69d052e.png)

**Comment by stenington** [comment]
The "Created by" text could actually be a link to the issuer site too, although that doesn't work for the rest of the badges we're demoing with really. :/

**Comment by stenington** [comment]
Oh, so in order to be able to add these to a pathway they _have_ to end up in the listing too.
