### ISSUE TITLE
Pathway progess indicator

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#260]
We should have a checklist indicator for you to mark as an indicator of you earning/completing a skill. Can elaborate on this more wt @zzzndr / pull some quick designs.

**Comment by zzzndr** [comment]
Version 1
https://redpen.io/kh740f16b0a4c3005c
In this proposal badges which are not earned are black/white (using css?), badges which are earned are in clolour & have an unobtrusive green ‘√’ in the top left of the badge container

Version 2
https://redpen.io/zq30f93300f10748a3
In this proposal badges which are not earned are black/white (using css?), badges which are earned are in clolour

**Comment by threeqube** [comment]
If the delta is the check mark, I feel like it's superfluous. But defer to @chloeatplay :smiley_cat:

**Comment by zzzndr** [comment]
totally agree that the checkmark alone isn't enough (:
the idea is to have the combination of the checkmark & coloured badges

if that is to subtle perhaps a coloured container background is more obvious, didn't go for that sollution so far because i assumed it meant more work for the dev's (:

**Comment by stenington** [comment]
@zzzndr @chloeatplay I'm wondering if the progress indicator should only show on your pledged pathways, or if it should show for any pathway you're viewing when you're logged in? On the one hand it might influence people to pledge a pathway if they see they already have a few of the badges, but on the other all pathways will be totally grayscale for people who haven't earned any badges yet which is a bit drab. What do you think?

**Comment by zzzndr** [comment]
good point about the earned badges on un-pledged pathways (:
i would show the progress indicator on any pathway when logged in (:

**Comment by stenington** [comment]
Relevant conversation in #308
