### ISSUE TITLE
Add About/ FAQ pages

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#261]
As per @zzzndr's designs TBD shortly

**Comment by zzzndr** [comment]
here are 2 links redpen pages with margins (:

margins About page
https://redpen.io/pf9af9d8f2de6b6fac

margins FAQ page
https://redpen.io/wsa597bf962fb52ad4

**Comment by chloeatplay** [comment]
Pages should say "About" not "Help" . Full text will be ready next week, need to get it copy-proofed by someone in communications team.

**Comment by ZeeJab** [comment]
Soundz good!! :rabbit:

**Comment by stenington** [comment]
Throwing this back to ready... seems like there's more work once we talk to comms.

**Comment by chloeatplay** [comment]
This is dependant on this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1014053 ETA ==> next Thursday.

**Comment by chloeatplay** [comment]
Updated copy is here https://openbadges.etherpad.mozilla.org/discovery-copy?

cc @ZeeJab  can you update? (Also needs to say About not Help on the top navigation)

merci :panda_face:
