### ISSUE TITLE
Add criteria from spreadsheet to badge display page

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#262]
We will design a quick way to do this with @zzzndr

**Comment by stenington** [comment]
@chloeatplay @LucasBlair Are you comfortable writing html in the spreadsheets? I could just plug that in unescaped to make paragraphs and lists. Otherwise we'll have to agree on some way for me to know what's free text and what should be in a list.

**Comment by chloeatplay** [comment]
yup, we can use unordered lists, for each criteria correct? ==>
< ul >  
  < li >  This  < /li >
  < li >  Without the spaces  < /li >
< /ul >

Overall : can we have a sentence that says "To get this badge you need to:" before every criteria list begins?
