### ISSUE TITLE
Indicate core badges in spreadsheet

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#263]

**Comment by stenington** [comment]
@LucasBlair @chloeatplay Could a badge be a core badge for one pathway, but not another in the spreadsheet?

**Comment by LucasBlair** [comment]
Yes, although I can't think of any examples from our current set of badges the system should probably accommodate it. One person could think a badge is super important and another person making a similar pathway might disagree.

**Comment by stenington** [comment]
Ok. The system accommodating it isn't a problem, I'm just wondering how expressive the spreadsheet format in particular needs to be.

**Comment by stenington** [comment]
@chloeatplay @LucasBlair I'm considering changing the way pathways are expressed in the spreadsheet in a way that would allow core badges to be defined, and even positions on the pathway to be defined in the spreadsheet. Would that be useful?

**Comment by chloeatplay** [comment]
@LucasBlair @stenington we should think about demo needs. If in our current examples there is no badge that lives as both a core and non core one, then we shouldn't build that functionality in, right?

**Comment by LucasBlair** [comment]
That sounds awesome Mike.

**Comment by chloeatplay** [comment]
:+1:

**Comment by stenington** [comment]
@chloeatplay Yep, I agree about not building things "just in case" at this point. Here though I think we can make a pretty easy change and get a lot of power out of it so I'll start on that.

**Comment by chloeatplay** [comment]
sounds good!
