### ISSUE TITLE
Design badge visuals healthcare & service

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#264]
Ello! For these, since they are not so significant we should design a placeholder visual- i.e. the same for all badges. @LucasBlair will indicate the 2 pathways we will demo from this category in the google excel. For those it would be nice to have some versatility. :game_die:

**Comment by chloeatplay** [comment]
@zzzndr is this done? if so letz cloze it!

**Comment by zzzndr** [comment]
all the badge visuals are added to the doc, it's all done!

**Comment by chloeatplay** [comment]
:pray:
