### ISSUE TITLE
Build milestones functionality

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#27]
Add the ability to mark milestones on the grid.

**Comment by threeqube** [comment]
@chloeatplay is this in scope of MVP?

**Comment by stenington** [comment]
It's unclear; I think we need to see how things go and didn't want to forget about it in the meantime.

**Comment by threeqube** [comment]
@stenington got it

**Comment by stenington** [comment]
Replaced by more detailed tickets.
