### ISSUE TITLE
Demo on 5-wide

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#279]
It might present better if the pathway editor is 5 wide instead of 3, since we'll be presenting in desktop resolution. The editor is configurable width-wise so if this is simple we can try it out.

**Comment by chloeatplay** [comment]
:thumbsup:

**Comment by stenington** [comment]
http://discovery-279.herokuapp.com/ defaults to 5 columns in the editor, and you can specify different column widths by adding `?columns=10` to the end of the url on a pathway or pledged pathway page to show 10 columns, for example.
