### ISSUE TITLE
Undo only undoes 1 delete

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#282]
There's a funny interaction between undo and nedb, I think, where:
1. undoing a delete adds the model back to the collection
2. the add fires a PUT request with the model data including _id
3. nedb doesn't let you set _id, so a new _id is generated
4. the _id gets updated on the client, firing a change event
5. the change event gets added to undo history
6. the next undo gets caught in a loop of undoing _id which immediately gets changed back

**Comment by threeqube** [comment]
whoa...

**Comment by stenington** [comment]
<img src="https://lh6.googleusercontent.com/-BOYdZI6tT7Y/UJwzRKYdQNI/AAAAAAAC5js/Ltg-gd6SCQQ/w506-h405/photo.jpg">

**Comment by threeqube** [comment]
that gif....is :fireworks:
