### ISSUE TITLE
Pathway editor square styling

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#290]
Make 'em pretty

**Comment by stenington** [comment]
@zzzndr Right now we're having a text overflow problem with badges in the editor. 

![screen shot 2014-05-13 at 6 25 18 pm](https://cloud.githubusercontent.com/assets/55319/2964987/918f234a-daed-11e3-9c7c-737fae23ca42.png)

How would you like me to make the text fit? Should I wrap the text and shrink the image so that two lines fit only where two lines are needed, or should the badge image always be the same smaller size even if the text fits in one line?

**Comment by zzzndr** [comment]
what are the font settings?

in the design they are:
Open Sans Regular
font-size 14px

**Comment by zzzndr** [comment]
but to answer your question as well (:
i think that if we have to choose between those 2 options i would go for same smaller size for all the images!

**Comment by stenington** [comment]
Ok, I can try just dropping the font size first and seeing how that works.

**Comment by chloeatplay** [comment]
This looks good :point_right: So stylish!
