### ISSUE TITLE
Make sure header with dropdown isn't eclipsed

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#293]
It gets eclipsed and hence unclickable sometimes on the dashboard page

**Comment by stenington** [comment]
This shows a div eclipsing the `<nav>` element. It sometimes, but not always, seems to prevent me from clicking the dropdown.
![screen shot 2014-05-13 at 10 23 10 pm](https://cloud.githubusercontent.com/assets/55319/2966346/bca8ed4c-db0e-11e3-9c3e-a5c6a0107d57.png)

**Comment by chloeatplay** [comment]
:+1:
