### ISSUE TITLE
Add more filters to ze hamburger 

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#295]
In the :hamburger: menu we should add the following filters:  webliteracy, technology, healthcare, service, cross career

**Comment by chloeatplay** [comment]
Ah, commented earier- we neez Ze webliterazy filter :v:

**Comment by stenington** [comment]
Oh right, skipped it because I didn't see it on any badges. Do you know how it will be written out? i.e. "#Web Literacy", "#webliteracy", etc.

**Comment by chloeatplay** [comment]
#Web Literacy  

also since we re on it ;) cross-career ==> #Cross Career (I will make that note to Luke et all)

**Comment by stenington** [comment]
Ok, #Web Literacy added and #Cross Career corrected!
