### ISSUE TITLE
Fix styling in pathway edit buttons

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#297]
When you edit the pathway, cancel buttons are not styled right. 
:point_right: 
![discover open badges 2014-05-13 15-27-58](https://cloud.githubusercontent.com/assets/1945209/2962837/c296198a-dad4-11e3-9112-c14c222792b7.png)

**Comment by chloeatplay** [comment]
cc @zzzndr can you provide the raight files? grazie!

**Comment by chloeatplay** [comment]
Looks wonderful- nitty picky thingie ===> x should be a few pixels to the left

**Comment by ZeeJab** [comment]
okii!
