### ISSUE TITLE
Fix cut off buttons

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#298]
When we add badges, then the buttons in that section are clipped off. Stupid buttons.
![bug_addbuttonscut](https://cloud.githubusercontent.com/assets/1945209/2962856/fbf9eb66-dad4-11e3-8583-036078f37f18.png)

**Comment by chloeatplay** [comment]
so fixed they are! :+1: grazie Lady @ZeeJab

**Comment by ZeeJab** [comment]
:rabbit: you're most welcome!
