### ISSUE TITLE
"new" icon has to be styled

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#299]
So it looks pretty @zzzndr can you provide the "new" icon link? :pray: 
![newthingie](https://cloud.githubusercontent.com/assets/1945209/2963175/19ed2a86-dad8-11e3-9992-ca5b9fdd7cf6.png)

**Comment by zzzndr** [comment]
voila:
https://www.dropbox.com/s/bh386pyqg9yj1rg/badgeNew.svg

**Comment by chloeatplay** [comment]
perfection! :+1:
