### ISSUE TITLE
Fix squares in pathway editor so text wraps

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#300]
wrap rap rap :musical_keyboard:

**Comment by ZeeJab** [comment]
@chloeatplay can you include an image of how it's broken right now? :rabbit:

**Comment by chloeatplay** [comment]
You ask I deliver :point_right: 
![discover open badges 2014-05-13 16-08-31](https://cloud.githubusercontent.com/assets/1945209/2963386/6e346eb8-dada-11e3-99c2-2b5abf6c21e7.png)

**Comment by ZeeJab** [comment]
uhhhh, perfection. thank you thank you :koala:

**Comment by chloeatplay** [comment]
looks good! :thumpsup:
