### ISSUE TITLE
new user avatar icon

### ISSUE THREAD

**Issue by zzzndr** [mozilla/openbadges-discovery#318]
a more suitable icon has to be created

**Comment by zzzndr** [comment]
@chloeatplay 

here is a link to 2 new variations (:
https://redpen.io/np25ce62d0c217f549

the yellow background stayed to help the icon popup out from the background & the dark blue makes sure there is no relation to skin colour (:

**Comment by threeqube** [comment]
Ha! How very kanye.

**Comment by zzzndr** [comment]
@stenington 

Here is the link to the new avatar
https://www.dropbox.com/s/gcxvjrj17q3s631/avatar2.svg
