### ISSUE TITLE
create 5 new pathway badge visuals

### ISSUE THREAD

**Issue by zzzndr** [mozilla/openbadges-discovery#319]

**Comment by zzzndr** [comment]
@chloeatplay 

Here is a link to 5 badge visuals based on the default badge visuals created at an earlier stage
https://redpen.io/fc2aa0d9e7c432f9e5

**Comment by zzzndr** [comment]
here are new badge visuals for review:
https://redpen.io/fdd83d1cf760cc9e0a

**Comment by zzzndr** [comment]
here is a redpen with badge visuals for all 5 pathway badges
https://redpen.io/wm77bfd2586e190106

**Comment by zzzndr** [comment]
all the pathway badge visuals are linked in the google doc

**Comment by chloeatplay** [comment]
zis is done and they look wonderful
