### ISSUE TITLE
create remaining tech badge visuals

### ISSUE THREAD

**Issue by zzzndr** [mozilla/openbadges-discovery#320]

**Comment by zzzndr** [comment]
@chloeatplay 

here are the visuals to review of the remaining tech badges (:
https://redpen.io/mgf942082952e61abe

**Comment by zzzndr** [comment]
and here is a new version of 'Kills bugs dead' & 'Pixel Pusher' (:

https://redpen.io/grb1380d7ff9e7517e

**Comment by chloeatplay** [comment]
ahahhaha- @zzzndr the kills bugs dead made me die :laughing:

**Comment by threeqube** [comment]
Ha :bug: splatter.
