### ISSUE TITLE
Fix styling of text in badge detail page

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#326]
Currently not all the text looks the same grey or is the same style. Look at that black text :black_circle: :black_large_square: :black_medium_small_square: :black_medium_square: 
![discover open badges 2014-05-16 12-13-55](https://cloud.githubusercontent.com/assets/1945209/2999369/1b8b1170-dd15-11e3-8bb4-de74ea06ab13.png)

It should be grey :rabbit:

**Comment by zzzndr** [comment]
here is the colour code: #4d4f53

**Comment by ZeeJab** [comment]
is that color for all text on the site? cuz we have h1, h3 and p's set as that atm?

**Comment by zzzndr** [comment]
correct, all the black text should have this text colour
except for the lighter grey text like the issuer of a badge on the landing page for instance (:

**Comment by stenington** [comment]
Wait I think this is still wrong.

**Comment by ZeeJab** [comment]
is it the `<li>`'s?

**Comment by stenington** [comment]
Yeah, looks like the list is `#222`

**Comment by ZeeJab** [comment]
I think if you add `li` to this list `h1, h2, h3, p { color: $text-dark; }` in styles.scss it'll be fine, unless that specific section is over specified for some reason?
