### ISSUE TITLE
When completing a pathway ==> sthg should happen

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#328]
@zzzndr I believe has screens for this :)

**Comment by zzzndr** [comment]
Here is a deep link to the wiki
https://github.com/mozilla/openbadges-discovery/wiki/Discovery-Pathway-UI-Design#d12--m12

I can imagine when the pathway is completed this popup is shown, also whenever you revisit a completed pathway.

• Body text:
Open Sans Regular
font size: 16px
font colour: #4d4f53
font colour name completed pathway: #0fa1d6

• Social media buttons:
font size: 50px
color: #0fa1d6
http://fortawesome.github.io/Font-Awesome/icon/facebook-square/
http://fortawesome.github.io/Font-Awesome/icon/twitter-square/
http://fortawesome.github.io/Font-Awesome/icon/google-plus-square/

• Link to the banner:
https://www.dropbox.com/s/hm354ssbatiax9a/banner.svg

• The page is covered with a black shape set to 40% transparancy

• Dimensions white popup window:
width: 600px
height: 430px
rounded corners: 15px

![sd_dimensions-popup](https://cloud.githubusercontent.com/assets/6721026/3002384/19077e6a-dd3e-11e3-991c-b6973ddfef1d.png)

It would be great if the header will change into this, but can imagine that is too time consuming at this point (:

![sd_header-completed-pathway](https://cloud.githubusercontent.com/assets/6721026/3002386/2118ea8a-dd3e-11e3-8512-f3772cd8cc52.png)

**Comment by chloeatplay** [comment]
So after all we agreed that this should be a simple message under the banner possibly that says " Congratulations, you did it! Now go ahead and give yourself a pat in the back."

**Comment by stenington** [comment]
I can add in the "Completed!" banner pretty easily I think. @zzzndr can you give me https://www.dropbox.com/s/u4tlf0t0rl6s9dp/banner.svg cut into three pieces: the left part where the banner folds, a thin slice of the middle part, and the right banner fold?

**Comment by zzzndr** [comment]
voila!
https://www.dropbox.com/s/nqhlp3bk3ml3tyw/banner_L.svg
https://www.dropbox.com/s/i8y9es8pmmu57fj/banner_M.svg
https://www.dropbox.com/s/1a6k9tkrl9oe1ko/banner_R.svg
