### ISSUE TITLE
Mobile Safari dragging bug

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#33]
Mobile Safari 7 on my phone offsets the badge image when dragging like so (my finger would be on the green square overlapping the yellow target):

<img src="https://f.cloud.github.com/assets/55319/2010562/874fd69e-876f-11e3-949b-6cfae32bfe8e.png" width="300">

For some reason the calculated `max-height` changes on the badge image when `.ui-draggable-dragging` is added to the containing `.badge` element, and it overflows to display below. It doesn't happen on desktop browsers that I've noticed.

**Comment by chloeatplay** [comment]
Wondering if this bug still open? cc @stenington

**Comment by stenington** [comment]
Nope, definitely not still valid.
