### ISSUE TITLE
Button rollovers

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#335]
Ideally the white "View more" button should have a blue rollover, and the help and faq links in the header an orange rollover.

@zzzndr Can you provide screenshots and color values to show what they both should be?

**Comment by zzzndr** [comment]
the "view more" button is perfect the way it is atm

I would use #0fa1d6 as the rollover colour for the the help & faq buttons
![sd009_helprollover](https://cloud.githubusercontent.com/assets/6721026/3019241/bcb73c6e-df8f-11e3-84a9-6eda735e1a42.png)

**Comment by stenington** [comment]
This got fixed at some point!
