### ISSUE TITLE
Explore pathway representation

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#34]
It just sort of clicked in my head that the way we've divided data between the discovery and directory projects puts the burden of doing cool recommendations stuff with badges and pathways on this project.

To that end, we may want to schedule some time to play around with different ways of representing a pathway in a database, and the repercussions of doing so. In particular, it may be worth exploring some graphing databases like [Neo4j](http://www.neo4j.org/) to see if that would provide a significant advantage over cobbling something together in mysql.

**Comment by threeqube** [comment]
@stenington when would be an appropriate time for that conversation?

**Comment by stenington** [comment]
@brianloveswords brought this up for consideration as well:  http://nodejsconfit.levelgraph.io/ 

To answer @threeqube, I think we should start the discussion pretty soon. There's not a lot I can do without knowing what DB to use for the project and getting team input will help me make a more informed decision.

**Comment by stenington** [comment]
The outcome of discussion with @threeqube and @chloeatplay was that there seems to be time to explore this a bit further, so I'll do a bit more research.

**Comment by brianloveswords** [comment]
If you need a Document/Graph hybrid approach, http://en.wikipedia.org/wiki/OrientDB looks interesting.

**Comment by stenington** [comment]
Oh woah, I missed the previous comment until just now.

OrientDB does look interesting. It'd be cool to play with it and find out just how, um, _twangy_ its dialect of SQL is. I wonder if you can treat it like SQL until you need graphs, or if you can't even get going without a pretty thorough understanding of the variations.

Anyway, I'd say the outcome of this exploration is a resounding "Let's use a graph database!" although it's hard to decide for certain which to use up front. The good news is that there actually seems to be a level of conceptual consistency between them so it's not like switching would mean starting from zero.

I think I'm going to move forward with neo4j for now and if it proves itself to be unsuitable I'll revisit some alternatives.
