### ISSUE TITLE
Have app not periodically forget everything for demo

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#341]

**Comment by stenington** [comment]
~~The quickest strategy here is to pay the $34.50 for 2 dynos on heroku, which means they'll stop putting the app to sleep which is when the data resets.~~

But note that **this is not a long-term strategy**. The app is just holding data in memory, so I imagine there's going to be a relatively low upper limit on the amount of data it can hold before it starts to slow down badly or consume too many resources and falls over. With the current data strategy, periodically forgetting everything is _a good thing_!

If we want the app to keep running and persisting data beyond the demo, we need to migrate to a real database.

**Comment by chloeatplay** [comment]
Let's do this for now, and reassess in the summer?

**Comment by jpcamara** [comment]
Actually, it clicked now that you said it's all in memory so this is probably not a viable solution. Even though the dyno will no longer go to sleep after a period of inactivity with this approach, it's still possible for the dynos to be restarted anyway.
https://devcenter.heroku.com/articles/dynos#automatic-dyno-restarts

Sorry if what I am saying is not accurate, as I don't know the internals of discovery. But I believe the problem is the in-memory nedb store, right?

Nedb is designed to mimic mongodb, and is supposed to be a fairly seamless transition to it if needs grow beyond what nedb provides. The solution might be to addon a free mongodb instance in heroku, and use mongo instead. I also thought of persisting the nedb store somehow, but I don't think it'd work very deterministically with multiple processes reading and writing from it.

Anyways, if I'm way off-base ignore me! :dancer:

**Comment by andrewhayward** [comment]
If it's just a problem of inactivity, is @jdotpz not setting up monitoring? Will that regular ping keep the dyno awake?

**Comment by stenington** [comment]
Oh, weird. Didn't know about the restarts separate from sleeping. :(

**Comment by stenington** [comment]
Ok, so looks like paying for extra dynos should _reduce_ the frequency of data wipes, but they'll still happen at least daily, and possibly more often even with regular pings, as I understand it. Turns out the solution for persistence is to... you know... use a persistent store. Which is not a huge surprise.

Good to hear the mongo transition is supposed to be easy.

**Comment by stenington** [comment]
Maybe I should fully unpack the skepticism underlying my last comment.

It _is_ actually nice that nedb implements a subset of the MongoDB API in a way, because that suggests that the upgrade path from nedb to mongo won't actually require an entire rewrite of the backend. But on the other hand, maybe an entire rewrite is the right thing to do for two reasons:
1. nedb does do a few things differently, as called out in the documentation. I know in at least one case, I have some funny workaround code for the fact that nedb doesn't let you set an `_id` (when undoing a delete and adding the object back), which apparently mongo is perfectly happy to let you do. Maybe that code will still be fine in mongo, maybe not... either way it will be slightly misleading or confusing to someone unfamiliar with the history of the project given that mongo doesn't have that particular constraint.
2. I'm worried that having a "real" db will give the backend a sense of legitimacy that it doesn't deserve. We really _shouldn't_ trust the code I've written, in my opinion. I wrote it as throwaway code knowing full well that nedb couldn't support production requirements. Porting it to work with mongo _without reviewing the crappy design decisions I made as well_ may start to solidify some really poor choices... a "prototype in production" scenario that I think we should avoid.

**Comment by andrewhayward** [comment]
@stenington - when have we ever put prototypes into production?!

**Comment by jdotpz** [comment]
Did this just start becoming a problem early this week or so?  I changed
the URL for this, so my health script was hitting the 301 instead of the
actual page.  I can repoint that if it'd be helpful?

**Comment by stenington** [comment]
@jdotpz discovery.openbadges.org is a splash page right now... I assume the health script is checking that, which is fine. The discussion here is about the heroku app which hasn't been launched and may or may not replace the splash page at that url.

**Comment by stenington** [comment]
@andrewhayward Heh, indeed. I actually probably shouldn't have used that phrase, because I have no problem making prototypes publicly available for whatever kind of usage they were built for. The backend of this app, as it stands, was built for one person to guide another person through it for about an hour. I don't relish the idea of putting it in a potentially more demanding scenario than that, fully hooked up to monitoring so it can make us all unhappy by crashing loudly all the time.

**Comment by stenington** [comment]
Ok, closing out this "for the demo" ticket in favor of #360
