### ISSUE TITLE
Design Discovery Dashboard

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#35]
This is a simple version of the dashboard as designed for responsive. Collecting feedback over here. https://redpen.io/h25y4j

**Comment by chloeatplay** [comment]
Added desktop version and reviewed position of "add a pathway" button. 
![discovery ux-updated-03](https://f.cloud.github.com/assets/1945209/2142841/626206c0-936a-11e3-9ae1-c7980b2823c0.png)

**Comment by threeqube** [comment]
[add a pathway] coming on 2nd screen does feel a bit more intuitive to me. :+1:

**Comment by chloeatplay** [comment]
Note: Each section above (i.e Badges, Wishlist) has a view more badges mode at the bottom.
