### ISSUE TITLE
Launching the prototype

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#350]
I want to understand the expectations for the launch of our prototype. My current understanding is that the current discover.openbadges.org splash page will come down and the app prototype will live there. 

Some general questions:
- [x] is it okay for user data as people play around to be periodically lost?
- [x] what kind of uptime is expected of the app?

Some specific technical concerns:
- [x] is it okay for us to point an openbadges url at a heroku instance?
- [x] is it okay to "launch" a prototype loading from a google spreadsheet?
- [x] do we need alerting?

**Comment by stenington** [comment]
@chloeatplay  We may need to spend some time addressing some questions about launching the prototype. It's a very hand-holdy thing right now... not a problem for the demo where I will indeed be holding its hand but afterwards the app could go down without us knowing. I'll need to research whether or not we need to move off heroku onto mofo infrastructure to add alerting, reboot, etc. and whether we need an alternative to a spreadsheet for the demo data. 

Apps generally don't run without someone caring for them, and I don't think we have any plan around that.

**Comment by chloeatplay** [comment]
Yup these are great questions, was wondering the same esp. re: who cares about this afterwards. Wondering if the "prototype" label & about sections could address some of these concerns ==> as in handling expectations. Also wondering how we handle this with other prototypes like AppMaker & WebLit Map. In general, we do want a functional URL that Gates can point to as a showcase for the project/prototype.

**Comment by stenington** [comment]
Yeah, but people only get to see the prototype label and about sections if the app hasn't crashed completely, which takes someone watching. :)

**Comment by chloeatplay** [comment]
good point :eyes: :eyes: :eyes: :eyes: :eyes: :eyes: :eyes: :eyes: 

cc @threeqube maybe badge alliance would be responsible for this?

**Comment by stenington** [comment]
I guess to elaborate on my previous thought, instead of making the app the thing at discover.openbadges.org, another option is to point to the app from the splash page with a note that it's a prototype and who to contact if it's down or something.

**Comment by chloeatplay** [comment]
Yeah, we _could_ do that- would need to pull together real fast a new splash page, but its doable.

**Comment by threeqube** [comment]
@chloeatplay I think it might be that BA continues to expand on conversations around discovery, pathways and discovery but not sure if it's in scope of active monitoring of Mozilla properties. But worth discussing if there's a need for that.

**Comment by davidascher** [comment]
- Heroku: yes, no problem, as long as JP's involved.
- loading from a google spreadsheet -- assuming you're talking about doing XHR calls to load Google Data API stuff, that should be fine, assuming the load is minimal.  
- alerting: easy enough to get JP to check a page for a 200 error code. we can do more if we need, but I doubt we need it.  File a bug w/ JP and tell him what URL to use.
- On the URL front: webmaker prototypes happen in the *.webmakerprototypes.org domain.  Probably not ideal for this.  

We could easily get discoveryprototype.org or equivalent.  If we want to do that there's a bugzilla process to do that, I can do it or JP can do it.

For the first two questions:
- data can be lost as long as user expectations re: data lifetime are met.  So making sure that the page is really crisp about the fact that people should expect the data to not live forever is key.
- uptime: if we have alerting and JP knows who to bug when the site goes down then we can see what uptime is.  I don't think we should spend much time on that until we have data.

**Comment by stenington** [comment]
Okay, cool. So pulling @jdotpz into the conversation... Hi @jdotpz!

With specifics forthcoming, it looks like we'll want to point a url (TBD) at a heroku app and have a super basic page check set up to make sure the thing hasn't completely crashed. I wanted to get that on your radar and ask where you'd like me to file bugs for that work when the time comes?

**Comment by jdotpz** [comment]
Please update this thread with an animated gif to ensure prompt service.

**Comment by stenington** [comment]
<img src="http://i.imgur.com/5ajbeWB.gif">

**Comment by jdotpz** [comment]
Very nice sir.

A few things to piggyback onto the previous conversation.
- [x] I think based on very little scale and ability to use New Relic and Opsview for alerting makes it a good fit on Heroku.  Also, it is much easier to hand it off to another group should that be necessary.
- [ ] We can easily to a landing page, or alternatively setup health checks which actually failover to a static site if we go down.  This is quite easy.
- [x]  New Relic!  I'd love to see this app have it.  It really is a good set of eyes on the app performance, and we can hang a lot of alerting off of it if needed.  
- [x] Please don't register the domain on our own.  It makes it so there is a long stretch (~1 - 2 months) where you can't transfer it, and then I can get MoCo to give us certs.
- [ ] I wouldn't be super upset if you filled this out with app info: https://docs.google.com/a/mozillafoundation.org/spreadsheet/viewform?usp=drive_web&formkey=dFBONmhPUXcxVVp5TFBiS0I4OWZ1RFE6MQ#gid=0 .  With that said, I know you are in crunch time, so we can get to that, as long as you promise. :)
- [x]  Get me a domain name and I'll get whirring on that.  Then we'll use our DNS to control it.

Thanks for taking the time to scope it out.  It is good to use the right tools for the job.
![righttool](https://cloud.githubusercontent.com/assets/1373628/3047377/eb0163aa-e134-11e3-92bb-6d195b1e6aa9.gif)

**Comment by stenington** [comment]
Okay, adding newrelic in #393

**Comment by stenington** [comment]
I requested access on that spreadsheet as well so I can fill it out.

**Comment by stenington** [comment]
And @chloeatplay can confirm but I think we're using discover.openbadges.org as the url?

**Comment by chloeatplay** [comment]
yah!
