### ISSUE TITLE
Design Pathway Landing Page_ Not Logged In

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#36]
Two iteration for the display of core badges and milestones that correspond to the badge system design by @LucasBlair. Wireframes & feedback over here https://redpen.io/c4n35y

**Comment by LucasBlair** [comment]
These look great Chloe.

**Comment by chloeatplay** [comment]
Went with line solution from two iterations above. Will explore more during UI. ![discovery ux_final-05](https://f.cloud.github.com/assets/1945209/2091025/f153e07a-8e9b-11e3-8883-7222b09067a5.png)

**Comment by threeqube** [comment]
:+1:

**Comment by chloeatplay** [comment]
Mike L: Instead of Pledge This, should be sign in to be able to pledge. This button appears every time you reach a pathway. Once pledged that pathway gets added to your pathways (on dashboard)
