### ISSUE TITLE
Refresh endpoint not removing old entries!

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#362]
OH NOES!

**Comment by chloeatplay** [comment]
:scream:

**Comment by chloeatplay** [comment]
@stenington we are currently experiencing a lot of badges not showing up, as well as a lot of doubles. Even though we have carefully defined only once badges with the keep value in the excel. Does this have to do with the above bug or should I file a new one?

**Comment by stenington** [comment]
This becomes moot with #360, if we merge it.
