### ISSUE TITLE
Pathways have descriptions and tags

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#369]

**Comment by chloeatplay** [comment]
This is done. I need a second pair of :eyes: to take a look. Will open a new ticket for reviewing demo-copy,  @SueSmith  could you help us check maybe?

**Comment by threeqube** [comment]
Yep can ask @SueSmith for a read through. Where can she locate it?

**Comment by chloeatplay** [comment]
Excellent thanks :pray: ===> its in the final badges excel, ping me on email so i can share setting and plan a walk through of where to edit.

**Comment by threeqube** [comment]
:+1:
