### ISSUE TITLE
Design Pathway Page_ Logged in Landing Page

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#37]
Landing Pathway Page for when you log in:  https://redpen.io/3mbxaf

**Comment by chloeatplay** [comment]
Added a little design key to help with understanding the rules in the pathways. 
![discovery ux_final-06](https://f.cloud.github.com/assets/1945209/2091010/c4eb0360-8e9b-11e3-8265-13472142d45a.png)

**Comment by threeqube** [comment]
@chloeatplay is the [personalize] menu trigger below the fold?

**Comment by chloeatplay** [comment]
@threeqube yes, good catch!

**Comment by threeqube** [comment]
@chloeatplay feels like it shouldn't be, no?

**Comment by chloeatplay** [comment]
Hmmm- I see how it can be tricky. In my head it should be a sticky button- which means it always sticks on the top of the screen when you come to scroll to that point. Does that make sense?

**Comment by threeqube** [comment]
Makes sense. Thanks for clarifying @chloeatplay :dancer:
