### ISSUE TITLE
Create copy and place story bits

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#373]
Bit by bit. Happy to help with this

**Comment by chloeatplay** [comment]
From our notes from today @LucasBlair 

Kathy: elaborate on the storybit of her appreciating early on the social aspect of nursing.
Add a storybit about her experience globe trotting as part of a program

Brian: (chloe will add)
Storybit about Brooklyn.JS

Matt: add many storybits around his linear pathway. Tofu squizer, type 2 diabetes study, psychologist at a youth detention center.

Didiem: add storybits next to her internship and one for her diversity champion position

**Comment by LucasBlair** [comment]
bits added
