### ISSUE TITLE
Create Pathway Shapes

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#374]
:black_medium_small_square: :black_large_square: 
:black_large_square: 
:black_medium_small_square: :black_large_square:  :black_large_square: 
:black_large_square: 
:black_large_square: 
:black_large_square:

**Comment by chloeatplay** [comment]
Notes as per our work session today @LucasBlair 

*Issuer pathways as trees.
*Kathy pathway- as per screen shot
*Brian &Robs' pathways scattered shape
*Didiem: milestones- linear shape
*Matt: linear with tons of storybits
*James,Valentine, Nick F: simple cluster.

cc @stenington we are currently blocked from doing this since not all badges are showing up.

**Comment by chloeatplay** [comment]
note for @LucasBlair / most badges should appear now thanks to @stenington we should be good to go for creating the shapes here.

**Comment by LucasBlair** [comment]
@stenington is a hero. Shapes will be finalized tonight.

**Comment by LucasBlair** [comment]
Pathways updated.
