### ISSUE TITLE
Add the pathway images for the remaining pathways

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#378]

**Comment by chloeatplay** [comment]
@zzzndr Moving back to working since I think there was some confusion. This ticket is meant for adding the pathway images for the remaining pathways that do not have a cover image. Those are UMPC, Nursing Unit Director, Chef and Warehouse => you can use generic icons for these not faces to differentiate them as issuers.

**Comment by zzzndr** [comment]
here the are 3 pathway images (:
https://redpen.io/sge06f60485cea11b1

**Comment by zzzndr** [comment]
here is a new UMPC badge visual (:
https://redpen.io/dx10f91322c66aa067

**Comment by zzzndr** [comment]
the 3 pathway badges are added to the excel (:

**Comment by chloeatplay** [comment]
:top: :top: :top: :top: :top: :top:
