### ISSUE TITLE
Create visuals for new web literacy badges

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#379]

**Comment by zzzndr** [comment]
here is the redpen link to the new badges (:
https://redpen.io/nq20ce57ebc4a0ebf2

**Comment by chloeatplay** [comment]
These look great :+1: 
Missing:
Respect The Penguin
UNIXorn
Ruby On Rails
JQuery
API Times

**Comment by zzzndr** [comment]
voila!
https://redpen.io/bp3e69dfe8e59077c9

**Comment by chloeatplay** [comment]
Fab ==> lets move ahead, svgs and on the doc :dancing:

**Comment by zzzndr** [comment]
\o/

**Comment by zzzndr** [comment]
added to the doc

**Comment by chloeatplay** [comment]
:tada:

**Comment by threeqube** [comment]
There look awesome! :tada:
