### ISSUE TITLE
Design Pathway Page_ View Similar

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#38]
View Similar; updated to reflect saving options as well as what happens after you have selected some badges for shuffle https://redpen.io/3vyuws

**Comment by chloeatplay** [comment]
Changed "shuffle" language to "reload" indicated with an icon here- 
![discovery ux_final-07](https://f.cloud.github.com/assets/1945209/2090998/8ceecf1e-8e9b-11e3-8a2d-fd12c930daf9.png)

**Comment by threeqube** [comment]
:+1:

**Comment by threeqube** [comment]
@chloeatplay: The newest badge recommendations always populate the top first and then down if there are no empty grid spaces available.
