### ISSUE TITLE
Create visuals for 4 new cross career badges

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#380]
Animals and descriptions added in the excel. Can help with this.

**Comment by zzzndr** [comment]
here is a link to a new cangeroo & unicorn!
https://redpen.io/xoe51a9c0dfe2edb7b

**Comment by zzzndr** [comment]
and a new unicorn!
https://redpen.io/ax808fa7eaf3cc6f20

**Comment by zzzndr** [comment]
here is the updated unicorn (:
https://redpen.io/oq8ec541ccd2f337c0

**Comment by chloeatplay** [comment]
Super duper ==> lets update all new badganimals on the excel :dancer:

**Comment by zzzndr** [comment]
and they are added to the excel

**Comment by chloeatplay** [comment]
the :bomb:
