### ISSUE TITLE
Create new placeholder image for Pathways & Badges without an image

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#381]
This could be a blown up version of the pathway icon with the three connected bdges.

**Comment by zzzndr** [comment]
Here is a link to the general pathway visual
https://redpen.io/mv2d9dc8655d8e3e71

**Comment by zzzndr** [comment]
Here is a link to the default badge visual
https://redpen.io/utc5bf6b3f268e156e

**Comment by zzzndr** [comment]
the default pathway badge visual is added the tabs UMPC Pathway, Cook pathway & Warehouse Pathway

**Comment by zzzndr** [comment]
Here is a link to the default badge visual svg
https://www.dropbox.com/s/pq25wzfssdv84re/defaultBadge2.svg

**Comment by chloeatplay** [comment]
Cool, they both look super.
@zzzndr ==> A clarification that the UPMC, Cook & Warehouse pathways need their own simple images.
cc @stenington  ==> 
These two default visuals
Badge default: https://www.dropbox.com/s/pq25wzfssdv84re/defaultBadge2.svg
Pathways default: https://www.dropbox.com/s/yguwxmdqgw5dzpu/pw_defaultPathway.svg
Are meant to replace the current placeholder images for pathways & badges (the ones that look like the OB logo)
