### ISSUE TITLE
Super slow loading time 

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#384]
Hmmm. App takes a solid 30 secs to first load on my firefox/chrome/safari browser. Wonder if this has anything to do wt loading from the excel.

:snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail: :snail:

**Comment by stenington** [comment]
Does "first load" mean after telling it to refresh, or first going to the site? There are several possibilities for the slowness:
- after telling the site to refresh, it doesn't read the spreadsheet until someone requests a page and doesn't show the page until the spreadsheet gets parsed
- if heroku put the site to sleep, it has to wake it up before it can give you a page _AND_ parse the spreadsheet
- if it's always slow when you first visit, even if you know the site wasn't sleeping and hadn't been refreshed, there may be a problem we can address

I'd bet 30 second slowness has to do with things largely out of our control at this stage, unfortunately.

**Comment by stenington** [comment]
This would hopefully go away with #360 (or at least decrease greatly) as db reloads would only happen on-demand, not every time the app had been sleeping. Of course waking up from sleep would still happen occasionally.
