### ISSUE TITLE
Featured pathways floating to the top of gallery listing

### ISSUE THREAD

**Issue by LucasBlair** [mozilla/openbadges-discovery#385]
Just a suggestion, but I think having the official pathways always be at the top of the Discover page would make it more clear which ones we want people to see first. It will also make it easier to test. It is difficult to find them amongst the clones sometimes. @stenington @chloeatplay

**Comment by chloeatplay** [comment]
I see the becoming a really annoying issue once people start even playing around with the prototype once we have a url as the gallery will feature the newest things. Not sure how much work is to do the above @stenington Could a quick fix be that we do a reverse listing, and list the older ones first - while removing the latest title on the top? that way the pathways we created will always be at the top?

**Comment by stenington** [comment]
We decided the way to do this was to tag featured pathways with #Featured, and I'll add a "Featured" filter to the dropdown that just uses that tag and make the default view that view.
