### ISSUE TITLE
Review final demo copy

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#386]
I should probably not be the one doing this. But we need a copy-ninja to review copy for the pathway descriptions, final & cross career badges, and storybits we are demoing.
cc @SueSmith if she can help us.

**Comment by SueSmith** [comment]
Sure! Can do whenever.. :smiley_cat:

**Comment by chloeatplay** [comment]
Thanks @SueSmith updated copy with your fab edits. Grazie mille :tada:

**Comment by SueSmith** [comment]
nae bother! :ghost:
