### ISSUE TITLE
User Test Discover

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#387]
cc @emgollie  currently working on a script here, https://openbadges.etherpad.mozilla.org/discovery-usertesting any suggestions for questions would be ah-mazing.

**Comment by emgollie** [comment]
@chloeatplay My notes were minor and I'm happy to discuss live tomorrow. Sander had a question about what you're sharing at the bottom of the pad that I wanted to make sure you saw.

**Comment by chloeatplay** [comment]
User testing was a big success last night at the digital ready event, added extensive notes in the etherpad https://openbadges.etherpad.mozilla.org/discovery-usertesting  :point_right:  strongly encourage you guys to check it out. Can go over it during todays stand as well.

cc/ @zzzndr @stenington @LucasBlair @ghami @ZeeJab @threeqube

**Comment by zzzndr** [comment]
Wow, really useful feedback!
Wish I could have been there to see them playing with the app!

**Comment by threeqube** [comment]
I know! Great stuff. :a: :m: :a: :zzz: ing!

**Comment by LucasBlair** [comment]
Well done. Getting the tool in front of career counselor or advisors for feedback would be really nice too.

**Comment by emgollie** [comment]
Neat to see how they reacted to the purpose and the purposeful playfulness of the site. Did you get any feedback on where people would want to access this (as in device and environment: home, school, etc.), @chloeatplay?

**Comment by chloeatplay** [comment]
Hmm, great question @emgollie , a lot of them told me it reminded them of a game app or something they would use on their phone. Most of them had access to desktop computers only at their school or afterschool/community center. My assumption would be that they would want to access it directly from their phone.
