### ISSUE TITLE
Design Pathway Page_ Rearrange

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#39]
Wondering how the milestone gets rearranged. https://redpen.io/j8xtmv

**Comment by chloeatplay** [comment]
![discovery ux_final-08](https://f.cloud.github.com/assets/1945209/2090984/55649114-8e9b-11e3-906c-e6e639f2e482.png)
After comments on redpen, addressing the issue of what happend when milestones are rearranged; badges between them do not move.

**Comment by threeqube** [comment]
:+1:

**Comment by threeqube** [comment]
Desktop grid is 6 squares wide and mobile grid is 3. Depending on size of your screen, the grid will wrap. When it wraps, how are notes handled? What if someone intentionally put a note to the right of the badge but that note ends up wrapping to the next line?

@stenington: Easiest solution would be to make the grid width the same. 

@chloeatplay: For MVP let's keep the grid width the same. We can user test.
