### ISSUE TITLE
Add newrelic to app

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#393]
Add new relic reporting to the app.

**Comment by chloeatplay** [comment]
:bowtie:

**Comment by stenington** [comment]
IT'LL JUST MAKE @jdotpz SO HAPPY!
<img src="http://mashable.com/wp-content/uploads/2013/07/Jeremy-Renner.gif">

**Comment by stenington** [comment]
As a test, the instance at http://discovery-newrelic.herokuapp.com/ should be logging as "openbadges-discovery".

**Comment by ZeeJab** [comment]
![excited-baby](https://cloud.githubusercontent.com/assets/1824988/3176333/54939e3a-ec04-11e3-8710-ce9b21b6f552.gif)

**Comment by stenington** [comment]
Seems to be working to me, but I'll wait for @jdotpz to sign off. Of course if Heroku puts the app to sleep New Relic complains about not receiving data, but aside from that I can see graphs do graph things when I go poke around the site.
