### ISSUE TITLE
Created by not updating correctly on clone

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#394]
If Bob clones a pathway created by Sue, when Bob is logged in he sees "Created by you" which is correct, but everyone else sees "Created by Sue" on his pathway.

**Comment by stenington** [comment]
All we have right now when a user is logged in is their email address, so the only option really is to have it say "Created by bob@gmail.com" or whatever Bob's email is, continuing the above example.

**Comment by chloeatplay** [comment]
Hmm- we shoudn't reveal emails right? Maybe we can use whatever is the first part of the email? before the @ ?

**Comment by stenington** [comment]
Yeah, I guess I'm a little worried that even then someone might clone a pathway, see half of their email address on the landing page, decide they don't want it there but have no way to remove it other than emailing us and asking to have it changed or taken down or something. :/

I'm almost tempted to let this bug live until user profiles are properly addressed, or is that overly cautious?

**Comment by chloeatplay** [comment]
Hmm- what if we hided the "Created By..." aspect EVERYWHERE? Since its a prototype, does it really matter? Or add something silly- Created by foo, bloop, yaml?

**Comment by stenington** [comment]
Yep, both are possibilities. Seeing "Created by you" helps me identify which cloned pathway is mine if I haven't edited the name yet, so I kind of like it being there just for that. But I suppose we could just show "Created by you" or "Your pathway" or something on the clones I've made, and not show anything on the others...

Something silly also works, although I guess that might be a little confusing for people.

**Comment by chloeatplay** [comment]
Let's do that then ==>  But I suppose we could just show "Created by you" or "Your pathway" or something on the clones I've made, and not show anything on the others...
