### ISSUE TITLE
Narrow target platform/browsers

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#4]
As mentioned in #3, the more we can narrow our target platform/browsers the more we can focus on building features. To that end I'm wondering:
- what platform/browser will we use for our user testing?
- how do we expect people to find and use the final product at the end of the grant?

If we know anything about the computers we'd use for our user testing, that would be useful information now. Obviously if we plan to do user testing by walking around with an iPad showing people what we have, for example, it had better work well on an iPad.

Also, if we know of groups who plan to use this product at the end of the grant, it would be useful to ask them now what kinds of devices and browsers they have at their disposal.

**Comment by threeqube** [comment]
> what platform/browser will we use for our user testing?

For MVP, modern browsers only imho.

**Comment by chloeatplay** [comment]
_how do we expect people to find and use the final product at the end of the grant?_

As per Erin even though we have a target audience, we don't have a pilot necessarily for this grant period. So I would go with @threeqube 's suggestion.
