### ISSUE TITLE
Design Pathway Page_ Add badges

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#40]
Added the flow of what happens when you click on a badge https://redpen.io/986f4h

**Comment by chloeatplay** [comment]
![discovery ux_final-09](https://f.cloud.github.com/assets/1945209/2090940/ede3052a-8e9a-11e3-94d9-d39e48df7d41.png)
Take a look at the wireframe below @iamjessklein @xmatthewx ; is this how you imagined badge page been displayed, re: including status of badge such as owned(in backpack) and/or wishlisted?
![discovery ux_final-10](https://f.cloud.github.com/assets/1945209/2090957/0b560a12-8e9b-11e3-8b0c-e5bb4109244b.png)

**Comment by threeqube** [comment]
@chloeatplay question: do I click [add badges] from menu first and then click the badge to add? How is the check mark feedback triggered?

**Comment by chloeatplay** [comment]
Good question; I was thinking it's triggered upon click/ touch. There could also be a visual indication, such as everything is faded out until you click/add it. Makes sense?

**Comment by threeqube** [comment]
Makes sense. Thanks for answering my silly questions. :smile:

**Comment by stenington** [comment]
I don't think D11/M11 made it onto the wiki, did they?

**Comment by chloeatplay** [comment]
good catch- adding it now :thumbsup:

**Comment by threeqube** [comment]
Is there a [view more] option if there are more than 4 badges? @chloeatplay to clarify.

**Comment by chloeatplay** [comment]
Will update today to reflect view more & mobile.

**Comment by chloeatplay** [comment]
![discovery ux_updated-09](https://f.cloud.github.com/assets/1945209/2142799/e6360aba-9369-11e3-82db-0588593ce071.png)
