### ISSUE TITLE
Annoying corner

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#405]
is annoying.
(on banner, aligment seems a bit off)
![discover open badges 2014-06-09 17-01-30](https://cloud.githubusercontent.com/assets/1945209/3222655/4eb9f3ba-f019-11e3-89df-afd29ed6003f.png)

**Comment by stenington** [comment]
Oh right, that got introduced with the new background for the animation to play over top of. The background is properly centered on the page... I think the green within the file itself is slightly off center. @zzzndr can you fix?

**Comment by zzzndr** [comment]
Here are 2 screendumps taken on the mac, I don't have Windows to check unfortunately
1. In Firefox & Chrome the offset is 4 pixels
2. In Safari the offset is 5 pixels

Does that mean that something else might cause this bug as well?
To have a quick fix, shall I change the graphic to look good on Firefox & Chrome?
1. Firefox & Chrome
   ![debug-1_firefox](https://cloud.githubusercontent.com/assets/6721026/3247226/48f0f7de-f182-11e3-90a2-6d9fedd80d14.jpg)
2. Safari
   ![debug-1_safari](https://cloud.githubusercontent.com/assets/6721026/3247231/58c00498-f182-11e3-8d23-02b89037830d.jpg)

**Comment by threeqube** [comment]
whoa, that's so neat! pixel level granularity!

**Comment by stenington** [comment]
@zzzndr Hmm, let me check again and make sure it's not entirely a problem with the css then before asking for a new graphic.

**Comment by zzzndr** [comment]
okido!

**Comment by stenington** [comment]
So I made the background behind the header image purple and took a screen shot of the corners, comparing how far the image overhangs the white center column on each side:

![comp](https://cloud.githubusercontent.com/assets/55319/3248110/040462f6-f18b-11e3-9aa4-114a94243f6e.png)

As far as I can see the image is perfectly centered on Firefox, and the jag is because the green isn't centered at the bottom within the overall image.

The 1px discrepancy I'm still looking at, although I can imagine it's just a border width or margin that didn't get set to 0.

**Comment by zzzndr** [comment]
okido, i'll change the graphic asap!

**Comment by zzzndr** [comment]
here is a link to the updated header, hope this will be a fix
https://www.dropbox.com/s/svb2zyegxq03jit/landingHeaderDesktopBG_v2.svg

the dimensions have remained the same

**Comment by stenington** [comment]
Cool, pushed through to production and looks good to me. @zzzndr want to confirm?

**Comment by zzzndr** [comment]
looking good in Firefox & Chrome!
safari has a 1 pixel offset (:

**Comment by stenington** [comment]
@zzzndr what version of safari? I don't see it.

**Comment by zzzndr** [comment]
i'm running OSX 10.9 with safari Version 7.0.1
it's just 1 pixel though (:

![sd_safari](https://cloud.githubusercontent.com/assets/6721026/3249067/f39da3b4-f194-11e3-831f-61ceeb6f6d98.png)

**Comment by stenington** [comment]
Hmm, so looks fine in Safari 6.1.4. I'll have to figure out how to get my hands on 7.0.1 to debug.

It's possible this comes down to some crazy pixel rounding thing when your browser's viewport is sized to an odd pixel-width or something ridiculous, in which case it might be a bit of a rat-hole to try to fix.

**Comment by zzzndr** [comment]
ouch, sounds potentially time consuming

**Comment by chloeatplay** [comment]
I SAY WE CALL TRUCE ON THIS PIXEL WAR.
:laughing:

**Comment by zzzndr** [comment]
\o/
