### ISSUE TITLE
Design Pathway Page_ Add notes

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#41]
Two iterations on how to add notes based on sprint convos https://redpen.io/4q5vgw

**Comment by threeqube** [comment]
@chloeatplay how do you hover on mobile?

**Comment by iamjessklein** [comment]
Gave feedback on redpen. I am leaning towards the second iteration, mainly based on the fact that I imagine I would want to notate the pathway vs. the badge. 

Re: hover on mobile could be accomplished with two click or click and hold gesture

**Comment by threeqube** [comment]
> Re: hover on mobile could be accomplished with two click or click and hold gesture

Ah ok. Thanks!

**Comment by chloeatplay** [comment]
Thanks @iamjessklein for the hover wiz, was thinking that on click and press would work here. After some debate going for now with the note occupying a whole square for now and renaming it possibly to storybit or story badge- ideas? I think it is not just a note, it is anything that can be a non badge experience, tip, story, to-do. I also agree that a user is more likely to want to annotate the whole pathway rather than a specific back as @iamjessklein very wisely argued in her redpen comments.
![discovery ux_final-11](https://f.cloud.github.com/assets/1945209/2090935/ddecb88c-8e9a-11e3-85d9-56a4e1c4c9e6.png)

**Comment by threeqube** [comment]
:+1:
