### ISSUE TITLE
Design Pathway Page_ Remove

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#42]
Needs to be re-designed if notes are not occupying separate squares. https://redpen.io/e7szmh

**Comment by chloeatplay** [comment]
Going with notes occupying whole squares for now. Remove works similarly for both badges and notes.  ![discovery ux_final-12](https://f.cloud.github.com/assets/1945209/2090878/31585770-8e9a-11e3-9d8e-a3d627d88837.png)

**Comment by threeqube** [comment]
:+1:

**Comment by threeqube** [comment]
Implementation ticket to be created.
