### ISSUE TITLE
Design Directory Landing Page

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#43]
Minor redesign so top navigation buttons are not next to each other and thumbs don't press the wrong things :) https://redpen.io/nav4cp

**Comment by threeqube** [comment]
:+1:

**Comment by iamjessklein** [comment]
:+1:  

cc: @xmatthewx - reference so that we can start thinking about where pathways connect w/ BadgeKit

**Comment by chloeatplay** [comment]
Finalizing these so I can transfer to wiki :dancer: 
![discovery ux_final-02](https://f.cloud.github.com/assets/1945209/2090845/b7d71c9c-8e99-11e3-9a6a-d3c582cc81b6.png)
&
![discovery ux_final-04](https://f.cloud.github.com/assets/1945209/2090865/f1092eec-8e99-11e3-9118-012d71dc755a.png)

**Comment by threeqube** [comment]
:+1:

**Comment by threeqube** [comment]
Clarification: [Featured] will be both pathways and badges. 
Featured list will be curated likely by @LucasBlair and or @ghami 

Tags will generate both pathways and badges. These tags will be tagged by issuers.
