### ISSUE TITLE
Design Quiz

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#44]
Based on @ghami 's content, need to design quiz wireframes & visuals.

**Comment by chloeatplay** [comment]
First stab based on @ghami 's wireframes. Thinking of using the hexagon theme here.

**Comment by chloeatplay** [comment]
![discovery ux_final-01](https://f.cloud.github.com/assets/1945209/2091089/c94f082e-8e9c-11e3-9e96-7ec402356adc.png)

**Comment by threeqube** [comment]
:+1:

**Comment by chloeatplay** [comment]
cc @zzzndr to help with this.

**Comment by chloeatplay** [comment]
out of scope for now :pray:
