### ISSUE TITLE
Tag taxonomy

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#46]
As mentioned in #12, this can serve as a discussion thread for tag taxonomies.

Below is my understanding of the issue. (Please correct me if I'm wrong.)
## Overview

We've been talking about the pathways app having some sort of hierarchical view of all of the badges it knows about and being able to cluster them under the relevant job sectors, for example. An obvious mechanism for this sort of thing is tags, **but** there's an important piece to consider. The [assertion spec](https://github.com/mozilla/openbadges-specification/blob/master/Assertion/latest.md) allows tags, but those are **issuer supplied tags** only. Relying on those to form a hierarchical view of the badges ecosystem is problematic in a few obvious ways:
- what if issuer A uses "healthcare", issuer B uses "Health-Care", and issuer C uses "medicine" as their tags?
- what if an issuer doesn't tag their badge classes?
- what if an issuer adds incorrect or inappropriate tags to their badge class to boost it?

Additionally, we talked about identifying a user's [Holland Code](http://en.wikipedia.org/wiki/Holland_Codes), for example, and using that to match to badges. But again, would we then ask issuers to assign the appropriate Holland Codes to their badges? It's sounds more like the work for an expert 3rd party to do, but a) there's not currently a mechanism for that and b) tagging an ever-growing ecosystem seems daunting.
## Prototype vs. real world

The workaround we discussed for the purposes of prototyping was just to control the dataset on which we operate. E.g. rather than opening up the badge directory to the entire world, we'll populate it ourselves with data we manage. In that case, we _could_ hire an expert to tag each badge with a Holland Code (or whatever) and expect things to work. The tradeoff is that it becomes much less obvious how to then roll the system out to the world and expect it to keep working.
## Proposal

I suppose a sort of middle ground could be reached by using a person's quiz results to point them to other badges _currently in a pathway_, as opposed to any badge anywhere. Or alternatively we could allow tagging of pathways themselves, and use the quiz results to point people to certain pathways. I think that would have a few advantages:
- including a badge in a pathway acts as a rough filter that the badge isn't spam
- if people start to build spam pathways, we **do** have control of that DB and can block users or delete pathways, if needed
- we know we need to seed the discovery app with predefined pathways anyway, so it doesn't represent unreasonable extra work.

**Comment by stenington** [comment]
Uh, so my discussion of the issue turned into a proposal for a solution, but hey...

**Comment by threeqube** [comment]
> Or alternatively we could allow tagging of pathways themselves, and use the quiz results to point people to certain pathways.

Who tags the pathways?

**Comment by ghami** [comment]
Hi, I'd begun to consider some ideas for tagging pathways and badges. Trying to minimise confusion with too many tags to have to select from, I wondered about using the Holland Code (as it provides a general bucket aligned to certain industries, that people could be dropped into and open up certain pathway options for them) but also having issuers define something about their badge - again trying to keep these short, I used the general types that Doug Belshaw uses - Achievement, Attribute (need to check if this is correct), Attendance for something like the following: 

Tagging for badge issuers - 

Choose which applies to your badge:

Achievement  

> opens up list of Holland Code activity types (Select what the achievement shows what does the achievement show? Hint: if the badge shows the ability to think deeply about a subject, choose ‘Thinking’; if it is the ability to do something practical well, choose ‘Doing practical things’; if it relates to the ability to organise an event, choose ‘Organise things’)
> then opens up list of employability skills 

Attendance 

> tagged with ‘curiosity’, ‘interested’ (and other relevant employer attributes that attendance might demonstrate)

Attribute 

> opens up list of employability attributes (defined in discussions with partners)
> **The attribute list could become very long though so may not be practical

Or we could use the badge types Lucas has defined:

Tagging for pathway creators and badge issuers - 

Each badge issuer and pathway creator chooses which of the following 6 tags apply to their badge and pathway (relating to the Holland Code or other high level definition of what types of activities people gravitate towards / enjoy)

Choose all which apply to your badge / pathway

This badge / pathway relates to the following:

Doing practical things  (Tip: this badge / pathway might involve doing something practical, physical, athletic, mechanical, being outdoors, using tools, operating machines, working with your hands, working with animals and so on’

Thinking (Tip: this badge / pathway might involve intellectual pursuits, things which require people to be curious, methodical, rational, analytical, logical, It might include scholarly, scientific, technical, or medical subjects, reading, solving problems, performing experiments, conducting research etc)

Creating (Tip: this badge / pathway might involve creative pursuits, things which require people to be intuitive, sensitive, articulate, expressive. It might relate to things which are unstructured, original, nonconforming, innovative. Might involve feelings, imagination, inspiration, spontaneity and open-mindedness. Subjects might include ideas, abstractions, concepts etc)

Helping others (Tip: this badge / pathway might demonstrate character traits such as kindness, generosity, cooperation, patience, being caring, helpful, empathetic, tactful, friendly. Skills in socializing, helping others, teaching and tasks that involve teamwork, social interaction,relationship building, improvement of society etc)

Persuading others (Tip: this badge / pathway might involve adventurous pursuits, things which require people to be ambitious, assertive, extroverted, energetic, enthusiastic, confident, optimistic. Skills such as being persuasive, motivational, influencing others, being in charge, taking risks, debating, competing etc)

Organising (Tip: this badge / pathway might demonstrate conscientiousness, precision, accuracy, conservative, reliablity traits. Things which require people to be logical, efficient, orderly, organized, thorough, detail-oriented, follow the rules. Things like practical tasks, quantitative measurements, structured environments etc)

*\* The tips were to try to help people choose a relevant Holland Code bucket but I appreciate they might be a bit long?

So the thinking was:
- Perhaps by allowing tagging of pathways as well as badges, we could at least identify what general type of activity an earner enjoys, which puts them in a Holland Code defined bucket. 
- The Holland Codes could have a list of relevant careers / industries assigned to them so this would allow us to show pathways for relevant industries. 
- The additional information either taken from badge tags or by mining badge criteria, could help narrow down certain attributes and skills for specific industries and pathways in those industries even further

--- One of the things we are considering doing for Jisc advice to badge issuers is to pull out keywords (essentially tags) at the start of badge criteria, so if that info is mined, it could pick out additional issuer defined keywords, which might align with pathway defined keywords.

**Comment by ghami** [comment]
- Another option I'm reflecting on how clusters of badges could be used to define attributes and if so how, eg tenacity is likely to be demonstrated over time and potentially over a range of badges. Is there merit in allowing users to define attributes via a cluster of badges rather than just one badge?

**Comment by ghami** [comment]
Badge Types - extended

Interest badges
Group badges
Event badges (eg Internship badge, Conference badge)
Attribute badges (eg Tech enthusiast badge, Positive attitude badge)
Accreditation badges (eg Degree badge, Certification badge)
Proficiency badges (eg Coding skill badge, Kung foo badge)
Knowledge badges (Badges for thinking, analysing, or having general knowledge)
Habit badges (Badges that are earned for having a good habit over a period of time, eg Safety, Cleanliness)

**Comment by stenington** [comment]
The problem with trying to provide a consistent structure to issuer-supplied badge tags is that it might work for the industry partners we help right now, but doesn't scale to opening up pathways to the entire badge ecosystem. I think we need something simple and robust, rather than a complicated system relying on the badge issuer building their badges through a tool we control so they understand the tagging system.

**Comment by stenington** [comment]
@threeqube For tagging pathways, I imagine we would tag the pathways we seed the system with, but then tags would be editable when a person clones a pathway.

**Comment by threeqube** [comment]
@stenington gotcha. Thanks!
