### ISSUE TITLE
Listing page template

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#48]
See wireframes for [D1/M1](https://github.com/mozilla/openbadges-discovery/wiki/Discovery-UX-Wireframes#wiki-d1--m1) and [D2/M2](https://github.com/mozilla/openbadges-discovery/wiki/Discovery-UX-Wireframes#wiki-d2--m2)

Includes header, footer, filter dropdown, search bar, sign in/up.

Does **not** include the pathways/badges themselves, functionality behind any buttons/search, the quiz, or the user summary view when logged in.

**Comment by stenington** [comment]
@chloeatplay Will the "View More" button add badges/pathways to the page, or show a different set of 8? Is the page supposed to get longer and longer with each click?

**Comment by stenington** [comment]
Also, what will the "Sign Up Now" link do?

**Comment by chloeatplay** [comment]
@stenington a) correct the page is supposed to get longer with everyclick of the "view more"
b) Good question re: Sign Up Now ===> Initially had designed for more than persona login. For MVP lets merge login, sign up to one button that says login with persona or something along those lines. :+1: ?

**Comment by stenington** [comment]
I think this is complete as of 156ee732d3ebe733f507e6bfb5a95c4692698544. The "view more" will happen in #50.
