### ISSUE TITLE
Design Directory Wireframes (Responsive On Mobile)

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#5]
Per the teams' decision I started with the responsive wire-frames first. Below wireframes in sequence: from someone coming to the site, to them logging in (persona), to searching through the directory and checking their profile (dashboard). 

Will present these on Mondays 4pm Discovery Call & Plan is to iterate through them and address many questions that I am sure will come up during our NYC-Sprint :city_sunset: 

![discovery ux-08](https://f.cloud.github.com/assets/1945209/1891703/325feba4-7a42-11e3-9921-c6a56411581d.png)

_use numeration in pink to leave comments for specific wireframes_
*D3: I inserted @carlacasilli 's mention for a pre-assessment quiz so we could gather information to make suggestions, but not sure if that will make it to MVP. 

cc @stenington @threeqube

**Comment by threeqube** [comment]
> *D3: I inserted @carlacasilli 's mention for a pre-assessment quiz so we could gather information to make suggestions, but not sure if that will make it to MVP.

:+1: I sort of feel like we need this. If the person has no badges, it'll be quite an uninspired experience otherwise, no?
