### ISSUE TITLE
Implications of mixing badges and pathways

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#51]
The discovery app wants to treat badges and pathways as essentially identical things, but I have the sense that that's a little bit tricky to implement. For example if we want the directory project to be in charge of badges but also to have featured badges, it's starting to feel like we need to periodically import directory badges in to the discovery project and then do all the searching/filtering/etc. on the discovery side, further shifting the balance of work this way.

**Comment by stenington** [comment]
I'm thinking this through in a bit more detail and what it will mean to mix badges and pathways in the app given that they're not both in the directory. 

**Filters**
- **Featured**: Featuring a badge will mean pulling a copy or reference to it into the pathways DB. This is fine because it already happens with pathways, which point to BadgeClass nodes that will at least reference a badge class in the directory if not actually cache the data. Note that at the moment this would require some DB surgery to do, as there's no UI for marking featured items.
- **Latest**: So long as both systems timestamp, I think this is fine. Get a page of each and sort them together.
- **By type**: Easy. This is an unmixed view of badges or pathways. Just hit the appropriate DB/service.
- **By tag**: Because we're limiting it to **issuer-specified tags** this is okay. Tags will be attached to badges as per the spec, and we can add tags to our pre-populated pathways to match. 

**Search**
Search will **only work on badges**. The directory is doing the indexing and providing the search API, and it knows nothing about pathways.

**Favoriting**
Again, favoriting will have to pull a reference or copy of a badge into the pathways DB, but that should be okay.

**Comment by threeqube** [comment]
@stenington Should we rethink whether we should include pathways in the directory too?

**Comment by stenington** [comment]
Discussed this offline a bit; it's a question we can raise in the directory repo, but it feels like it would have some pretty far-reaching implications to me. Even if we did add them to the directory though, I think it would be a read-only sort of thing and the discovery project would need its own representation so whether we do or not doesn't have a huge impact on moving this project forward for the time.
