### ISSUE TITLE
Logged in user summary template

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#54]
This is just a small template to display a user summary in the upper right corner for a logged in user. See for example [D2/M2](https://github.com/mozilla/openbadges-discovery/wiki/Discovery-UX-Wireframes#wiki-d2--m2).

**Comment by stenington** [comment]
@chloeatplay I was just implementing the little user summary in the logged in landing page view (see below), and realized we don't have anywhere to collect users' names or let them set avatars yet. Persona just gives us an email address. 

![screen shot 2014-02-18 at 4 25 22 pm](https://f.cloud.github.com/assets/55319/2200509/3aae8a58-98e3-11e3-95d0-40c647938f11.png)

We could add a sign up page where people have to provide that sort of info, or I can just go with displaying an email address (and maybe default avatar or something) for now. What do you think?

**Comment by chloeatplay** [comment]
Good point! I think we can do with email for now instead of full name and random avatar from a set of predefined illustrations we design. Does that make sense?

**Comment by andrewhayward** [comment]
[Gravatar](http://gravatar.com)?

**Comment by stenington** [comment]
:confetti_ball: WELCOME BACK @andrewhayward! :confetti_ball: 

Yeah gravatar could be good. Looks like you can use your own default images for people who don't have one so that could be a good combo.

**Comment by chloeatplay** [comment]
Weee! @andrewhayward you have the secret formula for eeevryting! :baby: :baby_bottle: :beers: :tada:

**Comment by stenington** [comment]
Hmm... more questions. @chloeatplay Should the # badges be wishlisted, earned, wishlisted + earned, or something else? And then I assume # pathways is the number they have pledged?

**Comment by chloeatplay** [comment]
Ehemm, good question. I am not sure about this one but my instinct would be to say ==> # badges = owned , # pathways = pledged.

**Comment by threeqube** [comment]
>  my instinct would be to say ==> # badges = owned , # pathways = pledged

We can also start with this and @emgollie can test it out.

**Comment by emgollie** [comment]
@chloeatplay and I are discussing today. The idea is that I will update the plan and the team will test together.

**Comment by threeqube** [comment]
:+1:

**Comment by stenington** [comment]
I'm closing this ticket out with just the email displayed for now. Tickets #101 and #102 take care of adding in stats and avatars, etc.
