### ISSUE TITLE
User dashboard page template

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#56]
See [D3/M3](https://github.com/mozilla/openbadges-discovery/wiki/Discovery-UX-Wireframes#wiki-d3--m3).

This includes very little to start: just the header, footer, user name, avatar and description text with placeholder elements for the pathway/badge lists.

**Comment by malynda** [comment]
We're covering most of these elements in our pr for #57 :)

**Comment by chloeatplay** [comment]
2 :bird: :bird: s 1 :black_circle: : <===supposed to be a stone  

:thumbsup:
