### ISSUE TITLE
Design Pathway Page Wireframes (Responsive On Mobile)

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#6]
Following #5, this is the Pathway Flow. We have been using the grid from our earlier prototype with @stenington as a reference to design this. Especially interested in some feedback on the design by @LucasBlair re: how content will fit in, what are some challenges you see with current design. We ll be working on solidifying this flow over sprint as well with @xmatthewx who is working on the backend UX of the system via Badgekit :dart: 
![discovery ux-09-09](https://f.cloud.github.com/assets/1945209/1891865/32ec85fc-7a45-11e3-9428-148dcddc969d.png)
_You can use pink numeration to refer to specifc wireframes:)_
_As with issue #5 we will also discuss this on Mondays Discovery call to get through questions and clarify touch points_
cc/ @threeqube

**Comment by threeqube** [comment]
@chloeatplay for all the closed wireframe tickets, we should have corresponding implement tickets, no? cc/ @stenington

**Comment by chloeatplay** [comment]
Reorganizing, to break down these giant scrolls to smaller tickets that can be directly associated with implementation tickets. Final wireframes will live in a wiki.  Please hold- will have this done within the hour :dancer: :

**Comment by threeqube** [comment]
:+1:
