### ISSUE TITLE
Pledged pathway page template

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#62]
See [D5/M5](https://github.com/mozilla/openbadges-discovery/wiki/Discovery-UX-Wireframes#wiki-d5--m5).

Includes image, progress bar, editable name and description.

Does not include hooking up actual functionality or pathway grid.

**Comment by stenington** [comment]
@chloeatplay or maybe @zzzndr What should the editable view look like for changing the image, title, etc. of a pledged pathway?

**Comment by zzzndr** [comment]
@stenington  @chloeatplay Perhaps it’s for the best to wait for Chloe
We haven’t talked about it yet, but perhaps she does have ideas already

**Comment by chloeatplay** [comment]
@stenington could work similarly to how you change cover-photos on facebook if that makes sense. i.e. clicking the little icon leads to a browse a file interaction. Wondering if we can use something like  filepicker.io
Does this answer your question?
I will let @zzzndr respond re: visuals for this page.

**Comment by stenington** [comment]
@chloeatplay How about for editing text?

**Comment by chloeatplay** [comment]
Could open an edit pathway name box in the same page, with a cancel and save button- like this?
![detalu](https://f.cloud.github.com/assets/1945209/2272047/cdda749a-9f00-11e3-8bd4-1626bb4024fe.png)

**Comment by stenington** [comment]
I opened #154 to continue this work. The pledged pathway page exists and works otherwise, so I think this is closeable.

**Comment by chloeatplay** [comment]
:thumbsup:
