### ISSUE TITLE
Pathway grid rearrange view

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#66]
This includes a Backbone view that manages rearranging badges on the grid.

**Comment by stenington** [comment]
@chloeatplay @zzzndr Will the rearrange functionality also have `Save` and `Cancel` options?

**Comment by zzzndr** [comment]
I think the interaction would be easier without the save & cancel button & you can't destroy anything by rearranging right?

**Comment by chloeatplay** [comment]
+1 @zzzndr , i think in general we want to avoid extra clicks as much as possible :baby_chick:

**Comment by stenington** [comment]
Ok I did a spike on this and pushed the code to [heroku](http://openbadges-discovery.herokuapp.com). You'll see that when you pledge, the url changes from something like `/pathway/3` to `/pledged/3` and the tiles become draggable.

**Comment by stenington** [comment]
I'd like to bring the code into the main repo more cleanly than the spike does though, with tests, so no PR yet.

**Comment by chloeatplay** [comment]
Just played around with it, :white_large_square: :white_medium_small_square: :white_large_square: :white_large_square: :point_right:  super cool :sunglasses:   !!

**Comment by zzzndr** [comment]
Tested with safari, firefox & chrome on my laptop & it works like charm! very nice ((:
on my iphone with ios7 it works also perfectly  \o/

don't know if this is the right place, but when i go to heroku on my ipad3 only a light grey empty page is visible (:

**Comment by threeqube** [comment]
Super cool! :+1: having fun playing with this on my mobile while on the plane! :tada:

**Comment by stenington** [comment]
@zzzndr hmm, light grey empty page probably means there's a bug in the javascript. :( I'll open a separate ticket for it.

**Comment by stenington** [comment]
Okay I think this is closable. Some remaining details have been broken out into #150 and #153.
