### ISSUE TITLE
Pathway grid add view

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#68]
This includes a Backbone view that manages adding badges to the grid.

**Comment by stenington** [comment]
This is basically working, although the dummy data is sloppy. The list of addable items includes pathways right now, and the page doesn't filter for items you have already added.

**Comment by stenington** [comment]
Oh, newly added badges also aren't marked with a "new" flag or anything yet.

**Comment by stenington** [comment]
@chloeatplay and @zzzndr When does the "new" indicator go away? Do they have to move the badge or something?

**Comment by chloeatplay** [comment]
Hmm, good question, maybe it stays there for a set period of time or till they log in again?

**Comment by stenington** [comment]
Ok, I just made it so that the indicator goes away when they click the badge, but that can be changed if necessary.

**Comment by stenington** [comment]
THIS IS CLOSEABLE! :fist:

**Comment by stenington** [comment]
The code has not been merged, but has been pushed to http://openbadges-discovery.herokuapp.com

**Comment by threeqube** [comment]
Whoa! So many new features to play around with!!!! :koala: :frog:
