### ISSUE TITLE
Design Directory Wireframes (Desktop)

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#7]

**Comment by chloeatplay** [comment]
Moving some of the #5 wireframes for desktop 
![discovery ux-03](https://f.cloud.github.com/assets/1945209/1927770/9e1f1102-7e67-11e3-9a38-286062e3ee48.png)
First take on dashboard- 
![discovery ux-04](https://f.cloud.github.com/assets/1945209/1927771/aa04c8e0-7e67-11e3-9b09-7159938b4fa1.png)

**Comment by emgollie** [comment]
Re: the directory: great stuff @chloeatplay! Looking forward to testing a few different options for the dropdown menu contents.

**Comment by threeqube** [comment]
:+1:
