### ISSUE TITLE
Badge page template

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#76]
This is the basic template for the badge page as in [D11/M11](https://github.com/mozilla/openbadges-discovery/wiki/Discovery-UX-Wireframes#wiki-d11--m11). It will also need a logged out version.

**Comment by stenington** [comment]
Actually I should ask. @chloeatplay will the badge page be viewable for any badge even when logged out, or only badges a user has wishlisted or owns?

**Comment by chloeatplay** [comment]
I think viewable by anyone- the difference being that when viewed by you (logged in), you can have the status showing, i.e. wishlisted, in backpack etc.

**Comment by threeqube** [comment]
:+1:

**Comment by stenington** [comment]
I think this is done.
