### ISSUE TITLE
Organize tickets

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-discovery#86]
We're working to organize tickets into 2 or more releases, the first tightly constrained to be doable before June 1 and the second _hopefully_ achievable by then as well.

We'll probably take a "clickable wireframe" approach to v1, building out the front-end but using dummy data. Waiting to hear from @chloeatplay to see if we want to trade off some front-end pages or features for a slightly more sophisticated approach to data for v1 though.

I will tag `Code` tickets with their intended version after that.

**Comment by chloeatplay** [comment]
Milestones updated and tickets organized over here https://openbadges.etherpad.mozilla.org/demo-script.

**Comment by stenington** [comment]
v1 tickets are in their respective milestones! I think this is done for now, but feel free to reopen if you disagree.

**Comment by threeqube** [comment]
:+1:
