### ISSUE TITLE
Create Copy for splash page

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#90]
Started here: https://openbadges.etherpad.mozilla.org/discovery-copy

**Comment by chloeatplay** [comment]
cc/ @megcolek

**Comment by chloeatplay** [comment]
Final copy here cc @adiladiladil 

_Text in mailing list box:_  Oh! I love this. Email me updates please

_Section 1: red_
Title: Navigate Your Potential with Open Badges
Text: Explore an ecosystem of digital badges, created in partnership with industry leaders and professionals in emerging fields such as Technology, Healthcare and Service to discover learning opportunities that are right for you.

_Section 2: yellow_
Title: Got Badges? Now Pave Your Pathway.
Text: Discover a network of pathways that can be  personalized to meet your individual learning needs. Explore careers  through a map of digital badges that connects to specific learning experiences. Get inspired by the story of real world professionals who work in growing industry fields and pave your own career path.

_Section 3: blue_
Title: Advisory Group
Text: Based on recent labor market research findings, the Discovery project aims to address the needs and expectations of employers and high school youth entering the job market. This project is generously supported by the Bill and Melinda Gates foundation with input from an esteemed advisory group.

_Names for each of the pictures:_

Mike Marriner
Cofounder, Roadtrip Nation

John Dillow 
Co-founder, Workforce.io

Constance Steinkuehler
Co-Director, Games+Learning+Society Center
Wisconsin Institute for Discovery

Elisabeth (Lissa) Soep, PhD
Senior Producer & Research Director, Youth Radio

Brother Mike Hawkins
Associate Director and Lead Mentor for Digital Youth Network

Michael John's 
Senior Creative Director, Electronic Arts

Milton Chen 
Senior Fellow, The George Lucas Educational Foundation

**Comment by threeqube** [comment]
:+1:
