### ISSUE TITLE
Review clickable wireframes

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/openbadges-discovery#91]
cc @threeqube 
@stenington requested that we open a ticket to review the clickable wireframes.

**Comment by stenington** [comment]
Yup. Please call out any problems you see!

Here's a few urls to hit and look over:
- Listing page: http://openbadges-discovery.herokuapp.com/
  - use the login button to log in (`blah@mockmyid.com` will get you through persona quickly) and view again
- Badge detail: http://openbadges-discovery.herokuapp.com/badges/1
  - For a badge you've earned: http://openbadges-discovery.herokuapp.com/badges/1?earned=1
  - For a badge you've favorited: http://openbadges-discovery.herokuapp.com/badges/1?fav=1

Most buttons aren't hooked up yet. I can probably hook some of them up or fake out what should happen if that's helpful.

**Comment by stenington** [comment]
My questions for @chloeatplay:
- [x] What part of the listing page should be a link to the badge page? (Badge title? Image?)
- [x] How will users log out?
- [x] Should log in also be in the header so you can log in from other pages (like the badge page)?
- [x] What will the "Sign up now" link do?

**Comment by stenington** [comment]
One piece I know isn't right is the logged in user summary as discussed in #54. Right now it's just an email address in dark blue on a dark background. Not super useful.

Improving this and incorporating gravatar, etc. might roll over from this milestone. It's a bit of an orphan in our plan, so I threw it in here to get started.

**Comment by chloeatplay** [comment]
Will review these in detail manana;
For now answering questions above: 
1) What part of the listing page should be a link to the badge page? (Badge title? Image?) ==> I think we should include your _badge display flipover css thingie_, so when you click on the square it takes you to the badge page. Title and short description would be on the flipped side. Does that work?
2) How will users logout. Could add a <logout> item in the hamburger dropdown menu. 
3) Should log in also be in the header so you can log in from other pages (like the badge page)? Yes, how about where the avatar goes on the top right?
4) What will the "Sign up now" link do? Sign Up now = same as Log in at this point, since we are just
 using persona I guess. 

Re: gravatar #54 Lets create a ticket and move it to another milestone. Seems like low priority right now but agreed we shouldn't forget it.

**Comment by threeqube** [comment]
:+1:

**Comment by chloeatplay** [comment]
Reviewed clickable wireframes :thumbsup: 
Great work Mike :shipit: 
one small comment- assuming that when we implement UI status of heart will change to different color etc once clicked?

**Comment by zzzndr** [comment]
works perfectly here in firefox, safari & chrome (:

**Comment by stenington** [comment]
Thanks guys!

@chloeatplay The wishlist hearts should work now when you're logged in. Clicking them while logged out doesn't do anything yet, but I'm working on it.

**Comment by stenington** [comment]
@chloeatplay Oh, and another question: should clicking "View More" below the badges/pathways display a different set of 8, or should it add more and make the page get longer?

**Comment by stenington** [comment]
Never mind! Just saw the answer [here](https://github.com/mozilla/openbadges-discovery/issues/48#issuecomment-35331523).

**Comment by threeqube** [comment]
srsly @stenington this is awesome stuff! :100:
